apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brokkr-bridge.fullname" . }}-env
  labels:
    {{- include "brokkr-bridge.labels" . | nindent 4 }}
data:
  {{- include "brokkr-bridge.env" . | trim | nindent 2 }}
