-- GENERATED by sql-seed/45-zone.py — do not edit by hand.
-- Regenerate via `task sql-seed:run` (or run the generator directly).
-- Idempotent: safe to re-apply on every bring-up.
BEGIN;

-- sim zone 00000000-0000-0000-0000-111111111111 (sim-zone) → org=00000000-0000-0000-0000-000000000000
INSERT INTO "Zone" (id, name, "uuidSuffix", "organizationId", "updatedAt")
VALUES ('00000000-0000-0000-0000-111111111111', 'sim-zone', '11111', '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    "uuidSuffix" = EXCLUDED."uuidSuffix",
    "organizationId" = EXCLUDED."organizationId",
    "updatedAt" = NOW();
INSERT INTO "ZoneAddress" (
    id, type, "formattedAddress", "addressLineOne", "addressLineTwo", city,
    "stateOrProvince", "postalCode", country, "countryCode", latitude, longitude,
    timezone, "zoneId", "createdAt", "updatedAt"
) VALUES
    ('9d179020-73d2-5ae6-a9c6-b757cf222c77', 'PRIMARY'::"ZoneAddressType",
     '100 Brokkr Way, Austin, TX 78701, United States', '100 Brokkr Way', 'Suite 400',
     'Austin', 'TX', '78701', 'United States', 'US', 30.2672, -97.7431,
     'America/Chicago', '00000000-0000-0000-0000-111111111111', NOW(), NOW()),
    ('2e70becd-1c1a-54d6-8f29-24923633c59f', 'SHIPPING'::"ZoneAddressType",
     '500 Logistics Blvd, Dallas, TX 75201, United States', '500 Logistics Blvd', 'Dock 12',
     'Dallas', 'TX', '75201', 'United States', 'US', 32.7767, -96.7970,
     'America/Chicago', '00000000-0000-0000-0000-111111111111', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, "formattedAddress" = EXCLUDED."formattedAddress",
    "addressLineOne" = EXCLUDED."addressLineOne", "addressLineTwo" = EXCLUDED."addressLineTwo",
    city = EXCLUDED.city, "stateOrProvince" = EXCLUDED."stateOrProvince",
    "postalCode" = EXCLUDED."postalCode", country = EXCLUDED.country,
    "countryCode" = EXCLUDED."countryCode", latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude, timezone = EXCLUDED.timezone,
    "zoneId" = EXCLUDED."zoneId", "deletedAt" = NULL, "updatedAt" = NOW();

INSERT INTO "Contact" (
    id, name, title, email, phone, "contactType", "isShippingContact",
    "zoneId", "createdAt", "updatedAt"
) VALUES
    ('e49d1194-e78e-55ef-a9b9-736ff688dff3', 'Jordan Lee', 'Zone Operations Manager',
     'jordan.lee@brokkr.local', '+15125550100',
     'Main'::"ZoneContactType", TRUE, '00000000-0000-0000-0000-111111111111', NOW(), NOW()),
    ('f8f683df-1393-55da-93e8-9d12099770b6', 'Morgan Chen', 'Facilities Manager',
     'morgan.chen@brokkr.local', '+15125550101',
     'Main'::"ZoneContactType", FALSE, '00000000-0000-0000-0000-111111111111', NOW(), NOW()),
    ('1d783db5-93a2-56ba-8ecf-b08a0ce3c25a', 'Riley Patel', 'Network Engineer',
     'riley.patel@brokkr.local', '+15125550102',
     'Technical'::"ZoneContactType", FALSE, '00000000-0000-0000-0000-111111111111', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, title = EXCLUDED.title, email = EXCLUDED.email,
    phone = EXCLUDED.phone, "contactType" = EXCLUDED."contactType",
    "isShippingContact" = EXCLUDED."isShippingContact", "zoneId" = EXCLUDED."zoneId",
    "deletedAt" = NULL, "updatedAt" = NOW();

INSERT INTO "ZoneMaintenance" (
    id, "zoneId", reason, message, "expectedEndAt", "enabledAt", "enabledBy",
    "disabledAt", "disabledBy", "createdAt", "updatedAt"
)
SELECT '05d2064c-58f0-5e60-88ce-404f12c7a661', '00000000-0000-0000-0000-111111111111', 'Quarterly generator service',
       'Generator testing completed successfully.', NULL, NOW() - INTERVAL '30 days', u.id,
       NOW() - INTERVAL '29 days', u.id, NOW() - INTERVAL '30 days', NOW()
FROM "User" u WHERE u.email = 'brokkr@brokkr.local'
ON CONFLICT (id) DO UPDATE SET
    reason = EXCLUDED.reason, message = EXCLUDED.message, "expectedEndAt" = EXCLUDED."expectedEndAt",
    "enabledAt" = EXCLUDED."enabledAt", "enabledBy" = EXCLUDED."enabledBy",
    "disabledAt" = EXCLUDED."disabledAt", "disabledBy" = EXCLUDED."disabledBy", "updatedAt" = NOW();

INSERT INTO "ZoneMaintenance" (
    id, "zoneId", reason, message, "expectedEndAt", "enabledAt", "enabledBy",
    "disabledAt", "disabledBy", "createdAt", "updatedAt"
)
SELECT '878d5060-d001-5e91-9f44-92ae9bf24713', '00000000-0000-0000-0000-111111111111', 'Network fabric upgrade',
       'Network fabric upgrade completed successfully.',
       NOW() - INTERVAL '6 days', NOW() - INTERVAL '7 days', u.id,
       NOW() - INTERVAL '6 days', u.id, NOW() - INTERVAL '7 days', NOW()
FROM "User" u WHERE u.email = 'brokkr@brokkr.local'
ON CONFLICT (id) DO UPDATE SET
    reason = EXCLUDED.reason, message = EXCLUDED.message,
    "expectedEndAt" = EXCLUDED."expectedEndAt", "enabledAt" = EXCLUDED."enabledAt",
    "enabledBy" = EXCLUDED."enabledBy", "disabledAt" = EXCLUDED."disabledAt",
    "disabledBy" = EXCLUDED."disabledBy", "updatedAt" = NOW();
-- role=Bridge device (+ 1:1 Bridge row) for the zone-detail "Bridges" card.
-- organizationId is the org-ownership FK the admin Bridges view joins on
-- (Device.organization) and MUST equal zone.organizationId — without it the
-- bridge reads back with a null zone/org and looks disconnected from the zone.
WITH up AS (
    INSERT INTO "Device" (
        id, name, status, role, "deviceType",
        "zoneId", "supplierId", "organizationId", "updatedAt"
    ) VALUES (
        '00000000-0000-0000-0000-000000008000', 'sim-bridge', 'PLANNED'::"DeviceStatus",
        'Bridge'::"DeviceRole", 'Baremetal'::"DeviceType",
        '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000000', NOW()
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId",
        "supplierId" = EXCLUDED."supplierId", "organizationId" = EXCLUDED."organizationId", "updatedAt" = NOW()
    RETURNING id
)
INSERT INTO "Bridge" (id, "deviceId", "createdAt", "updatedAt")
SELECT gen_random_uuid(), id, NOW(), NOW() FROM up
ON CONFLICT ("deviceId") DO NOTHING;
-- sim zone 00000000-0000-0000-0000-111111111112 (den-1) → org=00000000-0000-0000-0000-000000000000
INSERT INTO "Zone" (id, name, "uuidSuffix", "organizationId", "updatedAt")
VALUES ('00000000-0000-0000-0000-111111111112', 'den-1', '11112', '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    "uuidSuffix" = EXCLUDED."uuidSuffix",
    "organizationId" = EXCLUDED."organizationId",
    "updatedAt" = NOW();
INSERT INTO "ZoneAddress" (
    id, type, "formattedAddress", "addressLineOne", "addressLineTwo", city,
    "stateOrProvince", "postalCode", country, "countryCode", latitude, longitude,
    timezone, "zoneId", "createdAt", "updatedAt"
) VALUES
    ('f8a49556-13a2-539e-bc7a-1d03a9cecc3a', 'PRIMARY'::"ZoneAddressType",
     '100 Brokkr Way, Austin, TX 78701, United States', '100 Brokkr Way', 'Suite 400',
     'Austin', 'TX', '78701', 'United States', 'US', 30.2672, -97.7431,
     'America/Chicago', '00000000-0000-0000-0000-111111111112', NOW(), NOW()),
    ('fbbf8f09-2d3e-500a-b70c-e4382d241cfd', 'SHIPPING'::"ZoneAddressType",
     '500 Logistics Blvd, Dallas, TX 75201, United States', '500 Logistics Blvd', 'Dock 12',
     'Dallas', 'TX', '75201', 'United States', 'US', 32.7767, -96.7970,
     'America/Chicago', '00000000-0000-0000-0000-111111111112', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, "formattedAddress" = EXCLUDED."formattedAddress",
    "addressLineOne" = EXCLUDED."addressLineOne", "addressLineTwo" = EXCLUDED."addressLineTwo",
    city = EXCLUDED.city, "stateOrProvince" = EXCLUDED."stateOrProvince",
    "postalCode" = EXCLUDED."postalCode", country = EXCLUDED.country,
    "countryCode" = EXCLUDED."countryCode", latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude, timezone = EXCLUDED.timezone,
    "zoneId" = EXCLUDED."zoneId", "deletedAt" = NULL, "updatedAt" = NOW();

INSERT INTO "Contact" (
    id, name, title, email, phone, "contactType", "isShippingContact",
    "zoneId", "createdAt", "updatedAt"
) VALUES
    ('20a9c6bd-1094-59e1-ba81-995af38b828c', 'Jordan Lee', 'Zone Operations Manager',
     'jordan.lee-1@brokkr.local', '+15125550100',
     'Main'::"ZoneContactType", TRUE, '00000000-0000-0000-0000-111111111112', NOW(), NOW()),
    ('ed8279d6-2fde-506f-b785-a0f4a03bce03', 'Morgan Chen', 'Facilities Manager',
     'morgan.chen-1@brokkr.local', '+15125550101',
     'Main'::"ZoneContactType", FALSE, '00000000-0000-0000-0000-111111111112', NOW(), NOW()),
    ('a6862662-fd1f-5590-8412-4e914714a769', 'Riley Patel', 'Network Engineer',
     'riley.patel-1@brokkr.local', '+15125550102',
     'Technical'::"ZoneContactType", FALSE, '00000000-0000-0000-0000-111111111112', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, title = EXCLUDED.title, email = EXCLUDED.email,
    phone = EXCLUDED.phone, "contactType" = EXCLUDED."contactType",
    "isShippingContact" = EXCLUDED."isShippingContact", "zoneId" = EXCLUDED."zoneId",
    "deletedAt" = NULL, "updatedAt" = NOW();

INSERT INTO "ZoneMaintenance" (
    id, "zoneId", reason, message, "expectedEndAt", "enabledAt", "enabledBy",
    "disabledAt", "disabledBy", "createdAt", "updatedAt"
)
SELECT 'dab725df-5754-5c06-baed-cd926e637b61', '00000000-0000-0000-0000-111111111112', 'Quarterly generator service',
       'Generator testing completed successfully.', NULL, NOW() - INTERVAL '30 days', u.id,
       NOW() - INTERVAL '29 days', u.id, NOW() - INTERVAL '30 days', NOW()
FROM "User" u WHERE u.email = 'brokkr@brokkr.local'
ON CONFLICT (id) DO UPDATE SET
    reason = EXCLUDED.reason, message = EXCLUDED.message, "expectedEndAt" = EXCLUDED."expectedEndAt",
    "enabledAt" = EXCLUDED."enabledAt", "enabledBy" = EXCLUDED."enabledBy",
    "disabledAt" = EXCLUDED."disabledAt", "disabledBy" = EXCLUDED."disabledBy", "updatedAt" = NOW();

INSERT INTO "ZoneMaintenance" (
    id, "zoneId", reason, message, "expectedEndAt", "enabledAt", "enabledBy",
    "disabledAt", "disabledBy", "createdAt", "updatedAt"
)
SELECT '3d891108-a3eb-522b-b76a-eac9de5abc01', '00000000-0000-0000-0000-111111111112', 'Network fabric upgrade',
       'Network fabric upgrade completed successfully.',
       NOW() - INTERVAL '6 days', NOW() - INTERVAL '7 days', u.id,
       NOW() - INTERVAL '6 days', u.id, NOW() - INTERVAL '7 days', NOW()
FROM "User" u WHERE u.email = 'brokkr@brokkr.local'
ON CONFLICT (id) DO UPDATE SET
    reason = EXCLUDED.reason, message = EXCLUDED.message,
    "expectedEndAt" = EXCLUDED."expectedEndAt", "enabledAt" = EXCLUDED."enabledAt",
    "enabledBy" = EXCLUDED."enabledBy", "disabledAt" = EXCLUDED."disabledAt",
    "disabledBy" = EXCLUDED."disabledBy", "updatedAt" = NOW();
-- role=Bridge device (+ 1:1 Bridge row) for the zone-detail "Bridges" card.
-- organizationId is the org-ownership FK the admin Bridges view joins on
-- (Device.organization) and MUST equal zone.organizationId — without it the
-- bridge reads back with a null zone/org and looks disconnected from the zone.
WITH up AS (
    INSERT INTO "Device" (
        id, name, status, role, "deviceType",
        "zoneId", "supplierId", "organizationId", "updatedAt"
    ) VALUES (
        '00000000-0000-0000-0000-000000008001', 'sim-bridge-den-1', 'PLANNED'::"DeviceStatus",
        'Bridge'::"DeviceRole", 'Baremetal'::"DeviceType",
        '00000000-0000-0000-0000-111111111112', '00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000000', NOW()
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId",
        "supplierId" = EXCLUDED."supplierId", "organizationId" = EXCLUDED."organizationId", "updatedAt" = NOW()
    RETURNING id
)
INSERT INTO "Bridge" (id, "deviceId", "createdAt", "updatedAt")
SELECT gen_random_uuid(), id, NOW(), NOW() FROM up
ON CONFLICT ("deviceId") DO NOTHING;
-- role=Bridge device (+ 1:1 Bridge row) for the zone-detail "Bridges" card.
-- organizationId is the org-ownership FK the admin Bridges view joins on
-- (Device.organization) and MUST equal zone.organizationId — without it the
-- bridge reads back with a null zone/org and looks disconnected from the zone.
WITH up AS (
    INSERT INTO "Device" (
        id, name, status, role, "deviceType",
        "zoneId", "supplierId", "organizationId", "updatedAt"
    ) VALUES (
        '00000000-0000-0000-0000-000000008002', 'sim-bridge-den-1-1', 'PLANNED'::"DeviceStatus",
        'Bridge'::"DeviceRole", 'Baremetal'::"DeviceType",
        '00000000-0000-0000-0000-111111111112', '00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000000', NOW()
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId",
        "supplierId" = EXCLUDED."supplierId", "organizationId" = EXCLUDED."organizationId", "updatedAt" = NOW()
    RETURNING id
)
INSERT INTO "Bridge" (id, "deviceId", "createdAt", "updatedAt")
SELECT gen_random_uuid(), id, NOW(), NOW() FROM up
ON CONFLICT ("deviceId") DO NOTHING;
-- admin ops fixture: zone permanently in maintenance (no bridges / fleet nodes)
-- sim zone 0dab6ea4-66ab-5c75-85d4-a2dbb8c37ab1 (sim-zone-maintenance) → org=00000000-0000-0000-0000-000000000000
INSERT INTO "Zone" (id, name, "uuidSuffix", "organizationId", "updatedAt")
VALUES ('0dab6ea4-66ab-5c75-85d4-a2dbb8c37ab1', 'sim-zone-maintenance', '37ab1', '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    "uuidSuffix" = EXCLUDED."uuidSuffix",
    "organizationId" = EXCLUDED."organizationId",
    "updatedAt" = NOW();

INSERT INTO "ZoneAddress" (
    id, type, "formattedAddress", "addressLineOne", "addressLineTwo", city,
    "stateOrProvince", "postalCode", country, "countryCode", latitude, longitude,
    timezone, "zoneId", "createdAt", "updatedAt"
) VALUES (
    '0fc5a14f-2f54-56ba-9e14-acc36b73f926', 'PRIMARY'::"ZoneAddressType",
    '200 Maintenance Rd, Austin, TX 78702, United States', '200 Maintenance Rd', NULL,
    'Austin', 'TX', '78702', 'United States', 'US', 30.2672, -97.7431,
    'America/Chicago', '0dab6ea4-66ab-5c75-85d4-a2dbb8c37ab1', NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, "formattedAddress" = EXCLUDED."formattedAddress",
    "addressLineOne" = EXCLUDED."addressLineOne", "addressLineTwo" = EXCLUDED."addressLineTwo",
    city = EXCLUDED.city, "stateOrProvince" = EXCLUDED."stateOrProvince",
    "postalCode" = EXCLUDED."postalCode", country = EXCLUDED.country,
    "countryCode" = EXCLUDED."countryCode", latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude, timezone = EXCLUDED.timezone,
    "zoneId" = EXCLUDED."zoneId", "deletedAt" = NULL, "updatedAt" = NOW();

INSERT INTO "Contact" (
    id, name, title, email, phone, "contactType", "isShippingContact",
    "zoneId", "createdAt", "updatedAt"
) VALUES (
    'd72330d2-43a5-5de1-90f7-e94d80a37218', 'Casey Brooks', 'Maintenance Lead',
    'casey.brooks@brokkr.local', '+15125550999',
    'Technical'::"ZoneContactType", FALSE, '0dab6ea4-66ab-5c75-85d4-a2dbb8c37ab1', NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, title = EXCLUDED.title, email = EXCLUDED.email,
    phone = EXCLUDED.phone, "contactType" = EXCLUDED."contactType",
    "isShippingContact" = EXCLUDED."isShippingContact", "zoneId" = EXCLUDED."zoneId",
    "deletedAt" = NULL, "updatedAt" = NOW();

INSERT INTO "ZoneMaintenance" (
    id, "zoneId", reason, message, "expectedEndAt", "enabledAt", "enabledBy",
    "disabledAt", "disabledBy", "createdAt", "updatedAt"
)
SELECT '4f44a47f-9723-56be-8424-5ebad5b3695e', '0dab6ea4-66ab-5c75-85d4-a2dbb8c37ab1', 'Cooling plant outage',
       'Zone offline for cooling plant repairs. ETA tomorrow.',
       NOW() + INTERVAL '1 day', NOW() - INTERVAL '2 hours', u.id,
       NULL, NULL, NOW() - INTERVAL '2 hours', NOW()
FROM "User" u WHERE u.email = 'brokkr@brokkr.local'
ON CONFLICT (id) DO UPDATE SET
    reason = EXCLUDED.reason, message = EXCLUDED.message,
    "expectedEndAt" = EXCLUDED."expectedEndAt", "enabledAt" = EXCLUDED."enabledAt",
    "enabledBy" = EXCLUDED."enabledBy", "disabledAt" = EXCLUDED."disabledAt",
    "disabledBy" = EXCLUDED."disabledBy", "updatedAt" = NOW();
COMMIT;
