-- GENERATED by sql-seed/46-prefixes.py — do not edit by hand.
-- Regenerate via `task sql-seed:run` (or run the generator directly).
-- Idempotent: safe to re-apply on every bring-up.
BEGIN;

-- prefix/vlan role primary
INSERT INTO "IpamPrefixVlanRole" (id, name, slug, weight, "updatedAt")
VALUES (gen_random_uuid(), 'Primary', 'primary', 1000, NOW())
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, "updatedAt" = NOW();
-- prefix/vlan role management
INSERT INTO "IpamPrefixVlanRole" (id, name, slug, weight, "updatedAt")
VALUES (gen_random_uuid(), 'Management', 'management', 1000, NOW())
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, "updatedAt" = NOW();

-- primary prefix 192.168.200.0/24 → zone=00000000-0000-0000-0000-111111111111
INSERT INTO "Prefix" (
    id, prefix, status, "isPool", role,
    "organizationId", "zoneId", "prefixRoleId",
    "dhcpMode", "gatewayIpId",
    "createdAt", "updatedAt"
) VALUES (
    '51dfb0b1-95b6-5009-ae09-6cc5cb65f3c9', '192.168.200.0/24'::cidr, 'ACTIVE'::"PrefixStatus", false, 'PRIMARY'::"IpamRole",
    (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111'), '00000000-0000-0000-0000-111111111111', (SELECT id FROM "IpamPrefixVlanRole" WHERE slug = 'primary'),
    NULL, NULL,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    prefix = EXCLUDED.prefix, status = EXCLUDED.status, role = EXCLUDED.role,
    "organizationId" = EXCLUDED."organizationId", "zoneId" = EXCLUDED."zoneId",
    "prefixRoleId" = EXCLUDED."prefixRoleId",
    "dhcpMode" = EXCLUDED."dhcpMode", "gatewayIpId" = EXCLUDED."gatewayIpId",
    "updatedAt" = NOW();
-- rendered_netplan off: remove the primary-prefix gateway
DELETE FROM "Gateway" WHERE id = '49cd4036-9b19-5700-afee-a92921301b45';
DELETE FROM "IpAddress" WHERE id = '238c474a-69c4-542d-8bca-b21589b67805';
-- management prefix 192.168.105.0/24 → zone=00000000-0000-0000-0000-111111111111
INSERT INTO "Prefix" (
    id, prefix, status, "isPool", role,
    "organizationId", "zoneId", "prefixRoleId",
    "dhcpMode", "gatewayIpId",
    "createdAt", "updatedAt"
) VALUES (
    '50c42ad4-7cb0-5926-9a47-b1ed7fd8afec', '192.168.105.0/24'::cidr, 'ACTIVE'::"PrefixStatus", false, 'MANAGEMENT'::"IpamRole",
    (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111'), '00000000-0000-0000-0000-111111111111', (SELECT id FROM "IpamPrefixVlanRole" WHERE slug = 'management'),
    NULL, NULL,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    prefix = EXCLUDED.prefix, status = EXCLUDED.status, role = EXCLUDED.role,
    "organizationId" = EXCLUDED."organizationId", "zoneId" = EXCLUDED."zoneId",
    "prefixRoleId" = EXCLUDED."prefixRoleId",
    "dhcpMode" = EXCLUDED."dhcpMode", "gatewayIpId" = EXCLUDED."gatewayIpId",
    "updatedAt" = NOW();
-- Unattached gateway IP (no interface → not a reservation)
INSERT INTO "IpAddress" (id, address, status, "organizationId", "updatedAt")
VALUES ('fb2f4b4b-131a-52c5-bf31-7c04fd138436', '192.168.105.2/24'::inet, 'ACTIVE'::"IpStatus", (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111'), NOW())
ON CONFLICT (id) DO UPDATE SET
    address = EXCLUDED.address, status = EXCLUDED.status,
    "organizationId" = EXCLUDED."organizationId", "updatedAt" = NOW();
-- Gateway on prefix 50c42ad4-7cb0-5926-9a47-b1ed7fd8afec
INSERT INTO "Gateway" (id, "routingPriority", "vrfId", "gatewayIpId", "prefixId", "createdAt", "updatedAt")
VALUES ('ac094463-5e6a-5975-b582-ea3ad3413a6a', 100, NULL, 'fb2f4b4b-131a-52c5-bf31-7c04fd138436', '50c42ad4-7cb0-5926-9a47-b1ed7fd8afec', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
    "gatewayIpId" = EXCLUDED."gatewayIpId", "prefixId" = EXCLUDED."prefixId",
    "routingPriority" = EXCLUDED."routingPriority", "updatedAt" = NOW();
COMMIT;
