-- GENERATED by sql-seed/50-devices.py — do not edit by hand.
-- Regenerate via `task sql-seed:run` (or run the generator directly).
-- Idempotent: safe to re-apply on every bring-up.

BEGIN;

ALTER TABLE "Device" DISABLE TRIGGER device_role_write_once;
INSERT INTO "Tag" (id, name, slug, color, "organizationId", "updatedAt")
VALUES ('a69af7e3-3690-5777-9f88-65b3ea6e0e5f', 'discovery-light', 'discovery-light', '#38bdf8',
    '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT ("organizationId", name) DO UPDATE SET
    slug = EXCLUDED.slug, color = EXCLUDED.color, "updatedAt" = NOW();
-- cpu-1 id=00000000-0000-0000-0000-000000000001 ipmi=192.168.105.10 primary=192.168.200.10 net=Public arch=amd64 zone=00000000-0000-0000-0000-111111111111
UPDATE "Device" SET "deletedAt" = NOW(), "updatedAt" = NOW()
WHERE "deletedAt" IS NULL AND "zoneId" = '00000000-0000-0000-0000-111111111111' AND name = 'cpu-1'
  AND id <> '00000000-0000-0000-0000-000000000001' AND "supplierId" = (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111');
DELETE FROM "DeviceSecret"
WHERE "deviceId" = '00000000-0000-0000-0000-000000000001' AND "zoneId" <> '00000000-0000-0000-0000-111111111111';
INSERT INTO "Device" (
    id, name, status, role,
    serial, "systemSerial", "chassisSerial", "baseboardSerial",
    "zoneId", "networkType",
    "supplierId",
    architecture, "updatedAt"
) VALUES (
    '00000000-0000-0000-0000-000000000001', 'cpu-1', 'ACTIVE'::"DeviceStatus", 'Server'::"DeviceRole",
    'SIM525400BC0001', 'SIM525400BC0001', 'SIM525400BC0001', 'SIM525400BC0001',
    '00000000-0000-0000-0000-111111111111', 'Public'::"DeviceNetworkType",
    (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111'),
    'amd64', NOW()
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, status = EXCLUDED.status, role = EXCLUDED.role,
    serial = EXCLUDED.serial,
    "systemSerial" = EXCLUDED."systemSerial", "chassisSerial" = EXCLUDED."chassisSerial",
    "baseboardSerial" = EXCLUDED."baseboardSerial",
    "zoneId" = EXCLUDED."zoneId", "networkType" = EXCLUDED."networkType",
    "supplierId" = EXCLUDED."supplierId",
    architecture = EXCLUDED.architecture,
    "deletedAt" = NULL, "updatedAt" = NOW();
INSERT INTO "Server" (id, "deviceId", "powerStatus", "createdAt", "updatedAt")
VALUES (gen_random_uuid(), '00000000-0000-0000-0000-000000000001', 'On'::"ServerPowerStatus", NOW(), NOW())
ON CONFLICT ("deviceId") DO NOTHING;
UPDATE "Server" SET "powerStatus" = 'On'::"ServerPowerStatus", "updatedAt" = NOW()
WHERE "deviceId" = '00000000-0000-0000-0000-000000000001';
UPDATE "Server" SET "storageLayouts" = '{"configs":[{"disk_group_name":"SIM_SSD_40GB","disk_type":"ssd","disks":[{"name":"sda","serial":"SIM525400BC0001","wwn":"0x500525400bc00010"}],"num_disks":1,"size_per_disk":42949672960,"capabilities":["direct","lvm"],"file_systems":["ext4","xfs"]}],"default":{"os_disks_group":{"group":"SIM_SSD_40GB","config":"lvm","file_system":"ext4","mountpoint":"/"},"data_disks_groups":[],"cold_storage_disks_groups":[]}}'::jsonb, "updatedAt" = NOW()
WHERE "deviceId" = '00000000-0000-0000-0000-000000000001';
UPDATE "Server" SET "netplanOverride" = NULL, "updatedAt" = NOW()
WHERE "deviceId" = '00000000-0000-0000-0000-000000000001';
DELETE FROM "StorageDrive" WHERE "deviceId" = '00000000-0000-0000-0000-000000000001';
INSERT INTO "StorageDrive" (id, name, type, serial, wwn, "sizeBytes", "deviceId", "updatedAt")
VALUES (gen_random_uuid(), 'sda', 'SSD'::"StorageDriveType",
    'SIM525400BC0001', '0x500525400bc00010', 42949672960, '00000000-0000-0000-0000-000000000001', NOW());
DELETE FROM "Cpu" WHERE "deviceId" = '00000000-0000-0000-0000-000000000001';
INSERT INTO "Cpu" (
    id, "socketIndex", model, vendor, architecture,
    "coreCount", "threadCount", capabilities, "deviceId", "updatedAt"
) VALUES (
    gen_random_uuid(), 0, 'QEMU Virtual CPU', 'QEMU', 'x86_64',
    2, 2, ARRAY[]::text[], '00000000-0000-0000-0000-000000000001', NOW()
)
ON CONFLICT ("deviceId", "socketIndex") DO UPDATE SET
    model = EXCLUDED.model, vendor = EXCLUDED.vendor, architecture = EXCLUDED.architecture,
    "coreCount" = EXCLUDED."coreCount", "threadCount" = EXCLUDED."threadCount",
    "updatedAt" = NOW();
INSERT INTO "Cpu" (
    id, "socketIndex", model, vendor, architecture,
    "coreCount", "threadCount", capabilities, "deviceId", "updatedAt"
) VALUES (
    gen_random_uuid(), 1, 'QEMU Virtual CPU', 'QEMU', 'x86_64',
    2, 2, ARRAY[]::text[], '00000000-0000-0000-0000-000000000001', NOW()
)
ON CONFLICT ("deviceId", "socketIndex") DO UPDATE SET
    model = EXCLUDED.model, vendor = EXCLUDED.vendor, architecture = EXCLUDED.architecture,
    "coreCount" = EXCLUDED."coreCount", "threadCount" = EXCLUDED."threadCount",
    "updatedAt" = NOW();
INSERT INTO "MemoryConfig" (
    id, "totalSizeMb", "populatedDimms", "totalSlots",
    "dimmSizeMb", "dimmType", "dimmSpeed", "configuredSpeed",
    "eccType", "configSummary", "deviceId", "updatedAt"
) VALUES (
    gen_random_uuid(), 2048, 1, 4,
    2048, 'DDR4'::"MemoryType", '3200 MT/s', '3200 MT/s',
    'NONE'::"MemoryEccType", '1x2GB DDR4 3200 MT/s', '00000000-0000-0000-0000-000000000001', NOW()
)
ON CONFLICT ("deviceId") DO UPDATE SET
    "totalSizeMb" = EXCLUDED."totalSizeMb",
    "populatedDimms" = EXCLUDED."populatedDimms",
    "totalSlots" = EXCLUDED."totalSlots",
    "dimmSizeMb" = EXCLUDED."dimmSizeMb",
    "dimmType" = EXCLUDED."dimmType",
    "dimmSpeed" = EXCLUDED."dimmSpeed",
    "configuredSpeed" = EXCLUDED."configuredSpeed",
    "eccType" = EXCLUDED."eccType",
    "configSummary" = EXCLUDED."configSummary",
    "updatedAt" = NOW();
INSERT INTO "DeviceFirmware" (id, type, vendor, version, date, "deviceId", "updatedAt")
VALUES
    (gen_random_uuid(), 'BIOS'::"FirmwareType", 'EDK2', 'sim-1.0', NULL, '00000000-0000-0000-0000-000000000001', NOW()),
    (gen_random_uuid(), 'BMC'::"FirmwareType", 'OpenIPMI', 'sim-1.0', NULL, '00000000-0000-0000-0000-000000000001', NOW())
ON CONFLICT ("deviceId", type) DO UPDATE SET
    vendor = EXCLUDED.vendor, version = EXCLUDED.version, "updatedAt" = NOW();
INSERT INTO "Gpu" (
    id, index, model, vendor, serial, "memoryTotalMb",
    "eccEnabled", "pcieLinkGen", "pcieLinkWidth", "vbiosVersion",
    "deviceId", "updatedAt"
) VALUES (
    gen_random_uuid(), 0, 'NVIDIA GeForce RTX 4090', 'NVIDIA'::"GpuVendor",
    'SIM-GPU-0001', 24576,
    false, 4, 16, 'sim-vbios-1.0',
    '00000000-0000-0000-0000-000000000001', NOW()
)
ON CONFLICT ("deviceId", index) DO UPDATE SET
    model = EXCLUDED.model, vendor = EXCLUDED.vendor, serial = EXCLUDED.serial,
    "memoryTotalMb" = EXCLUDED."memoryTotalMb",
    "eccEnabled" = EXCLUDED."eccEnabled",
    "pcieLinkGen" = EXCLUDED."pcieLinkGen", "pcieLinkWidth" = EXCLUDED."pcieLinkWidth",
    "vbiosVersion" = EXCLUDED."vbiosVersion",
    "updatedAt" = NOW();
INSERT INTO "DeviceSolConfig" (
    "deviceId", "solCapable", "solEnabled", "baudRate", "optimalPort", "availablePorts", "updatedAt"
) VALUES (
    '00000000-0000-0000-0000-000000000001', true, true, 115200, 'ttyS0', ARRAY['ttyS0']::text[], NOW()
)
ON CONFLICT ("deviceId") DO UPDATE SET
    "solCapable" = EXCLUDED."solCapable", "solEnabled" = EXCLUDED."solEnabled",
    "baudRate" = EXCLUDED."baudRate", "optimalPort" = EXCLUDED."optimalPort",
    "availablePorts" = EXCLUDED."availablePorts", "updatedAt" = NOW();
INSERT INTO "Interface"
    (id, name, type, enabled, "macAddress", "mgmtOnly", "deviceId", description,
     speed, mtu, "linkType", driver, operstate, "linkOperUp", "linkPhysicalUp", "markConnected", "updatedAt")
VALUES (gen_random_uuid(), 'eth0', 'ETHERNET_1G'::"InterfaceType", true,
    '52:54:00:da:00:01', false, '00000000-0000-0000-0000-000000000001', 'Primary data NIC',
    1000, 1500, 'ETHERNET'::"InterfaceLinkType", 'virtio_net', 'up', true, true, true, NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "macAddress" = EXCLUDED."macAddress",
    "mgmtOnly" = EXCLUDED."mgmtOnly", description = EXCLUDED.description,
    speed = EXCLUDED.speed, mtu = EXCLUDED.mtu, "linkType" = EXCLUDED."linkType",
    driver = EXCLUDED.driver, operstate = EXCLUDED.operstate,
    "linkOperUp" = EXCLUDED."linkOperUp", "linkPhysicalUp" = EXCLUDED."linkPhysicalUp",
    "markConnected" = EXCLUDED."markConnected", "updatedAt" = NOW();
INSERT INTO "Interface"
    (id, name, type, enabled, "macAddress", "mgmtOnly", "deviceId", description,
     speed, mtu, driver, operstate, "linkOperUp", "linkPhysicalUp", "markConnected", "updatedAt")
VALUES (gen_random_uuid(), 'IPMI', 'IPMI_BMC'::"InterfaceType", true,
    '52:54:00:bc:00:01', true, '00000000-0000-0000-0000-000000000001', 'BMC management interface',
    100, 1500, 'ipmi_si', 'up', true, true, true, NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "macAddress" = EXCLUDED."macAddress",
    "mgmtOnly" = EXCLUDED."mgmtOnly", description = EXCLUDED.description,
    speed = EXCLUDED.speed, mtu = EXCLUDED.mtu, driver = EXCLUDED.driver,
    operstate = EXCLUDED.operstate, "linkOperUp" = EXCLUDED."linkOperUp",
    "linkPhysicalUp" = EXCLUDED."linkPhysicalUp", "markConnected" = EXCLUDED."markConnected",
    "updatedAt" = NOW();
INSERT INTO "Interface"
    (id, name, type, enabled, "macAddress", "mgmtOnly", "deviceId", description,
     "linkType", guid, "maxSpeedGbps", mtu, "portState",
     driver, operstate, "linkOperUp", "linkPhysicalUp", "markConnected", "updatedAt")
VALUES (gen_random_uuid(), 'ib0', 'INFINIBAND_HDR'::"InterfaceType", true,
    NULL, false, '00000000-0000-0000-0000-000000000001', 'Sim InfiniBand / RDMA port',
    'INFINIBAND'::"InterfaceLinkType", '0x525400bc00010000', 200, 4092, 'ACTIVE',
    'mlx5_ib', 'up', true, true, true, NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "mgmtOnly" = EXCLUDED."mgmtOnly", description = EXCLUDED.description,
    "linkType" = EXCLUDED."linkType", guid = EXCLUDED.guid, "maxSpeedGbps" = EXCLUDED."maxSpeedGbps",
    mtu = EXCLUDED.mtu, "portState" = EXCLUDED."portState",
    driver = EXCLUDED.driver, operstate = EXCLUDED.operstate,
    "linkOperUp" = EXCLUDED."linkOperUp", "linkPhysicalUp" = EXCLUDED."linkPhysicalUp",
    "markConnected" = EXCLUDED."markConnected", "updatedAt" = NOW();
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('a69af7e3-3690-5777-9f88-65b3ea6e0e5f', 'DEVICE'::"TagObjectType", '00000000-0000-0000-0000-000000000001')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
DELETE FROM "IpAddress" WHERE "interfaceId" IN
    (SELECT id FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000001' AND name = 'IPMI' AND "deletedAt" IS NULL);
DELETE FROM "IpAddress"
WHERE address = '192.168.105.10'::inet AND "organizationId" = (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111')
    AND "vrfId" IS NULL AND "deletedAt" IS NULL;
INSERT INTO "IpAddress"
    (id, address, status, "organizationId", "interfaceId", "assignedObjectType", "assignedObjectId", "updatedAt")
SELECT gen_random_uuid(), '192.168.105.10'::inet, 'ACTIVE'::"IpStatus", (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111'),
    id, 'Interface'::"AssignedObjectType", id, NOW()
FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000001' AND name = 'IPMI' AND "deletedAt" IS NULL;
DELETE FROM "IpAddress" WHERE "interfaceId" IN
    (SELECT id FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000001' AND name = 'eth0' AND "deletedAt" IS NULL);
DELETE FROM "IpAddress"
WHERE address = '192.168.200.10/24'::inet AND "organizationId" = (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111')
    AND "vrfId" IS NULL AND "deletedAt" IS NULL;
INSERT INTO "IpAddress"
    (id, address, status, "organizationId", "interfaceId", "assignedObjectType", "assignedObjectId", "updatedAt")
SELECT gen_random_uuid(), '192.168.200.10/24'::inet, 'ACTIVE'::"IpStatus", (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111'),
    id, 'Interface'::"AssignedObjectType", id, NOW()
FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000001' AND name = 'eth0' AND "deletedAt" IS NULL;
DELETE FROM "IpAddress"
WHERE address = '198.51.100.10/32'::inet AND "organizationId" = (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111');

ALTER TABLE "Device" ENABLE TRIGGER device_role_write_once;
COMMIT;
