-- GENERATED by sql-seed/51-commissioning-devices.py — do not edit by hand.
-- Regenerate via `task sql-seed:run` (or run the generator directly).
-- Idempotent: safe to re-apply on every bring-up.

BEGIN;

ALTER TABLE "Device" DISABLE TRIGGER device_role_write_once;
-- commission-1 id=00000000-0000-0000-0000-000000000003 (role=null commissioning, dhcp) ipmi=192.168.105.12
UPDATE "Device" SET "deletedAt" = NOW(), "updatedAt" = NOW()
WHERE "deletedAt" IS NULL AND "zoneId" = '00000000-0000-0000-0000-111111111111' AND name = 'commission-1'
  AND id <> '00000000-0000-0000-0000-000000000003' AND "supplierId" = (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111');
DELETE FROM "DeviceSecret"
WHERE "deviceId" = '00000000-0000-0000-0000-000000000003' AND "zoneId" <> '00000000-0000-0000-0000-111111111111';
INSERT INTO "Device" (
    id, name, status, role, "deviceType",
    "zoneId", "networkType",
    "supplierId",
    architecture, "netplanOverride", "updatedAt"
) VALUES (
    '00000000-0000-0000-0000-000000000003', 'commission-1', 'PLANNED'::"DeviceStatus", NULL, 'Baremetal'::"DeviceType",
    '00000000-0000-0000-0000-111111111111', 'Public'::"DeviceNetworkType",
    (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111'),
    'amd64', NULL, NOW()
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, status = EXCLUDED.status, role = EXCLUDED.role,
    "deviceType" = EXCLUDED."deviceType",
    "zoneId" = EXCLUDED."zoneId", "networkType" = EXCLUDED."networkType",
    "supplierId" = EXCLUDED."supplierId",
    architecture = EXCLUDED.architecture, "netplanOverride" = NULL,
    "deletedAt" = NULL, "updatedAt" = NOW();
DO $$ BEGIN
    IF to_regclass('"ServerOperatingSystem"') IS NOT NULL THEN
        DELETE FROM "ServerOperatingSystem" WHERE "serverId" IN
            (SELECT id FROM "Server" WHERE "deviceId" = '00000000-0000-0000-0000-000000000003');
    END IF;
END $$;
DELETE FROM "StorageDrive" WHERE "deviceId" = '00000000-0000-0000-0000-000000000003';
DELETE FROM "Server" WHERE "deviceId" = '00000000-0000-0000-0000-000000000003';
INSERT INTO "DeviceSolConfig" (
    "deviceId", "solCapable", "solEnabled", "baudRate", "optimalPort", "availablePorts", "updatedAt"
) VALUES (
    '00000000-0000-0000-0000-000000000003', true, true, 115200, 'ttyS0', ARRAY['ttyS0']::text[], NOW()
)
ON CONFLICT ("deviceId") DO UPDATE SET
    "solCapable" = EXCLUDED."solCapable", "solEnabled" = EXCLUDED."solEnabled",
    "baudRate" = EXCLUDED."baudRate", "optimalPort" = EXCLUDED."optimalPort",
    "availablePorts" = EXCLUDED."availablePorts", "updatedAt" = NOW();
INSERT INTO "Interface"
    (id, name, type, enabled, "macAddress", "mgmtOnly", "deviceId", description, "updatedAt")
VALUES (gen_random_uuid(), 'eth0', 'ETHERNET_1G'::"InterfaceType", true,
    '52:54:00:da:00:03', false, '00000000-0000-0000-0000-000000000003', 'Primary data NIC', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "macAddress" = EXCLUDED."macAddress",
    "mgmtOnly" = EXCLUDED."mgmtOnly", "updatedAt" = NOW();
DELETE FROM "IpAddress" WHERE "interfaceId" IN
    (SELECT id FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000003' AND name = 'eth0' AND "deletedAt" IS NULL);
INSERT INTO "Interface"
    (id, name, type, enabled, "macAddress", "mgmtOnly", "deviceId", description, "updatedAt")
VALUES (gen_random_uuid(), 'IPMI', 'IPMI_BMC'::"InterfaceType", true,
    '52:54:00:bc:00:03', true, '00000000-0000-0000-0000-000000000003', 'BMC management interface', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "macAddress" = EXCLUDED."macAddress",
    "mgmtOnly" = EXCLUDED."mgmtOnly", "updatedAt" = NOW();
DELETE FROM "IpAddress" WHERE "interfaceId" IN
    (SELECT id FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000003' AND name = 'IPMI' AND "deletedAt" IS NULL);
DELETE FROM "IpAddress"
WHERE address = '192.168.105.12'::inet AND "organizationId" = (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111')
    AND "vrfId" IS NULL AND "deletedAt" IS NULL;
INSERT INTO "IpAddress"
    (id, address, status, "organizationId", "interfaceId", "assignedObjectType", "assignedObjectId", "updatedAt")
SELECT gen_random_uuid(), '192.168.105.12'::inet, 'ACTIVE'::"IpStatus", (SELECT "organizationId" FROM "Zone" WHERE id = '00000000-0000-0000-0000-111111111111'),
    id, 'Interface'::"AssignedObjectType", id, NOW()
FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000003' AND name = 'IPMI' AND "deletedAt" IS NULL;

ALTER TABLE "Device" ENABLE TRIGGER device_role_write_once;
COMMIT;
