-- GENERATED by sql-seed/55-dcim.py — do not edit by hand.
-- Regenerate via `task sql-seed:run` (or run the generator directly).
-- Idempotent: safe to re-apply on every bring-up.

BEGIN;

-- Manufacturers + device models (catalog for the Device-Models page)
INSERT INTO "Manufacturer" (id, name, slug, "updatedAt")
VALUES ('9edffaa3-4a6b-5816-a89e-ebf5b54908a6', 'Brokkr', 'brokkr', NOW())
ON CONFLICT (name) DO UPDATE SET
    slug = EXCLUDED.slug, "updatedAt" = NOW();
INSERT INTO "Manufacturer" (id, name, slug, "updatedAt")
VALUES ('8f065636-d59d-5799-aed4-3b2fd9bb5dc8', 'NVIDIA', 'nvidia', NOW())
ON CONFLICT (name) DO UPDATE SET
    slug = EXCLUDED.slug, "updatedAt" = NOW();
INSERT INTO "Manufacturer" (id, name, slug, "updatedAt")
VALUES ('d043ebd6-97c8-5034-8aa6-9fd8b2308c60', 'Eaton', 'eaton', NOW())
ON CONFLICT (name) DO UPDATE SET
    slug = EXCLUDED.slug, "updatedAt" = NOW();
INSERT INTO "Manufacturer" (id, name, slug, "updatedAt")
VALUES ('4cc03137-0dcb-5925-ac49-15169ecb7d88', 'Opengear', 'opengear', NOW())
ON CONFLICT (name) DO UPDATE SET
    slug = EXCLUDED.slug, "updatedAt" = NOW();
INSERT INTO "Manufacturer" (id, name, slug, "updatedAt")
VALUES ('5b70b666-6f8d-51e3-a146-fd4af309b13c', 'Generic', 'generic', NOW())
ON CONFLICT (name) DO UPDATE SET
    slug = EXCLUDED.slug, "updatedAt" = NOW();
INSERT INTO "Manufacturer" (id, name, slug, "updatedAt")
VALUES ('5e9cb42a-3b6e-5e8c-882b-dd91e8b870f9', 'Motivair', 'motivair', NOW())
ON CONFLICT (name) DO UPDATE SET
    slug = EXCLUDED.slug, "updatedAt" = NOW();
INSERT INTO "Manufacturer" (id, name, slug, "updatedAt")
VALUES ('1a8246ee-ca22-586b-a7a9-5559a246d353', 'Juniper', 'juniper', NOW())
ON CONFLICT (name) DO UPDATE SET
    slug = EXCLUDED.slug, "updatedAt" = NOW();

-- Manufacturer contacts
INSERT INTO "Contact" (
    id, name, title, email, phone, notes, "ticketingPortalUrl", website,
    "manufacturerId", "createdAt", "updatedAt"
)
VALUES (
    'cce85235-a1bb-588b-b1c2-0b5169aeb984', 'Taylor Example', 'Technical Support Engineer', 'nvidia-support@example.test', '+12025550120', 'Local simulator technical support contact.',
    'https://support.example.test/nvidia', 'https://nvidia.example.test',
    (SELECT id FROM "Manufacturer" WHERE name = 'NVIDIA'), NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, title = EXCLUDED.title, email = EXCLUDED.email,
    phone = EXCLUDED.phone, notes = EXCLUDED.notes,
    "ticketingPortalUrl" = EXCLUDED."ticketingPortalUrl", website = EXCLUDED.website,
    "zoneId" = NULL, "organizationId" = NULL, "manufacturerId" = EXCLUDED."manufacturerId",
    "contactType" = NULL, "isShippingContact" = FALSE, "deletedAt" = NULL, "updatedAt" = NOW();
INSERT INTO "Contact" (
    id, name, title, email, phone, notes, "ticketingPortalUrl", website,
    "manufacturerId", "createdAt", "updatedAt"
)
VALUES (
    'cff01534-b4b2-5f05-ab1f-87788614b8da', 'Jordan Example', 'Account Manager', 'eaton-sales@example.test', '+12025550121', 'Local simulator sales contact.',
    NULL, 'https://eaton.example.test',
    (SELECT id FROM "Manufacturer" WHERE name = 'Eaton'), NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, title = EXCLUDED.title, email = EXCLUDED.email,
    phone = EXCLUDED.phone, notes = EXCLUDED.notes,
    "ticketingPortalUrl" = EXCLUDED."ticketingPortalUrl", website = EXCLUDED.website,
    "zoneId" = NULL, "organizationId" = NULL, "manufacturerId" = EXCLUDED."manufacturerId",
    "contactType" = NULL, "isShippingContact" = FALSE, "deletedAt" = NULL, "updatedAt" = NOW();
INSERT INTO "DeviceModel" (id, manufacturer, model, slug, "formFactor", "heightU", "maxPowerW", "isFullDepth",
    description, "updatedAt")
VALUES ('7911aec0-a5d6-5e94-aa6f-c0f4066b900a', 'Brokkr', 'Sim Virtual Server', 'brokkr-sim-virtual-server', '2U', 2,
    800, true, 'Simulated bare-metal server (qemu)', NOW())
ON CONFLICT (manufacturer, model) DO UPDATE SET
    "formFactor" = EXCLUDED."formFactor", "heightU" = EXCLUDED."heightU", "maxPowerW" = EXCLUDED."maxPowerW",
    description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "DeviceModel" (id, manufacturer, model, slug, "formFactor", "heightU", "maxPowerW", "isFullDepth",
    description, "updatedAt")
VALUES ('05f7729c-4996-5c7b-b411-3b398bbdb46f', 'NVIDIA', 'SN2201', 'nvidia-sn2201', '1U', 1, 150, true,
    '48-port 1GbE management / ToR switch', NOW())
ON CONFLICT (manufacturer, model) DO UPDATE SET
    "formFactor" = EXCLUDED."formFactor", "heightU" = EXCLUDED."heightU", "maxPowerW" = EXCLUDED."maxPowerW",
    description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "DeviceModel" (id, manufacturer, model, slug, "formFactor", "heightU", "maxPowerW", "isFullDepth",
    description, "updatedAt")
VALUES ('2a43c1d3-10b3-56d0-ae99-f69ccd753a12', 'Eaton', '9001-22313', 'eaton-9001-22313', '0U', 0, 17000, true,
    'Rack-mount PDU, 24x C13 outlets', NOW())
ON CONFLICT (manufacturer, model) DO UPDATE SET
    "formFactor" = EXCLUDED."formFactor", "heightU" = EXCLUDED."heightU", "maxPowerW" = EXCLUDED."maxPowerW",
    description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "DeviceModel" (id, manufacturer, model, slug, "formFactor", "heightU", "maxPowerW", "isFullDepth",
    description, "updatedAt")
VALUES ('4fbaa00a-18cc-5d56-a76b-56b47ee9929e', 'Opengear', 'IM7248', 'opengear-im7248', '1U', 1, 30, true,
    '48-port serial console server (OOB)', NOW())
ON CONFLICT (manufacturer, model) DO UPDATE SET
    "formFactor" = EXCLUDED."formFactor", "heightU" = EXCLUDED."heightU", "maxPowerW" = EXCLUDED."maxPowerW",
    description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "DeviceModel" (id, manufacturer, model, slug, "formFactor", "heightU", "maxPowerW", "isFullDepth",
    description, "updatedAt")
VALUES ('3cd0b9d7-a412-5b89-9215-228f5183c57a', 'Generic', 'LC-24 Patch Panel', 'generic-lc-24-patch-panel', '1U', 1,
    NULL, true, '24-port LC fiber patch panel', NOW())
ON CONFLICT (manufacturer, model) DO UPDATE SET
    "formFactor" = EXCLUDED."formFactor", "heightU" = EXCLUDED."heightU", "maxPowerW" = EXCLUDED."maxPowerW",
    description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "DeviceModel" (id, manufacturer, model, slug, "formFactor", "heightU", "maxPowerW", "isFullDepth",
    description, "updatedAt")
VALUES ('468aea5a-0ab3-53b0-aadd-917000c0198e', 'Generic', 'Cat6A-48 Patch Panel', 'generic-cat6a-48-patch-panel', '1U',
    1, NULL, true, '48-port Cat6A copper patch panel', NOW())
ON CONFLICT (manufacturer, model) DO UPDATE SET
    "formFactor" = EXCLUDED."formFactor", "heightU" = EXCLUDED."heightU", "maxPowerW" = EXCLUDED."maxPowerW",
    description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "DeviceModel" (id, manufacturer, model, slug, "formFactor", "heightU", "maxPowerW", "isFullDepth",
    description, "updatedAt")
VALUES ('5fc9234b-04f1-503c-a33a-f3784567af54', 'Motivair', 'ChilledDoor CDU-40', 'motivair-chilleddoor-cdu-40', '0U',
    0, 2000, true, 'Rack-mount coolant distribution unit, 40kW', NOW())
ON CONFLICT (manufacturer, model) DO UPDATE SET
    "formFactor" = EXCLUDED."formFactor", "heightU" = EXCLUDED."heightU", "maxPowerW" = EXCLUDED."maxPowerW",
    description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "DeviceModel" (id, manufacturer, model, slug, "formFactor", "heightU", "maxPowerW", "isFullDepth",
    description, "updatedAt")
VALUES ('25a83468-bdc7-57d1-92de-1bb79044e7f4', 'Juniper', 'MX204', 'juniper-mx204', '1U', 1, 400, true,
    'Compact edge/aggregation router', NOW())
ON CONFLICT (manufacturer, model) DO UPDATE SET
    "formFactor" = EXCLUDED."formFactor", "heightU" = EXCLUDED."heightU", "maxPowerW" = EXCLUDED."maxPowerW",
    description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "DeviceModel" (id, manufacturer, model, slug, "formFactor", "heightU", "maxPowerW", "isFullDepth",
    description, "updatedAt")
VALUES ('a6c64108-824c-5f3b-9c6f-58619d6f92db', 'Generic', '1U Cable Brush Panel', 'generic-1u-cable-brush-panel', '1U',
    1, NULL, true, '1U rack cable-management brush panel', NOW())
ON CONFLICT (manufacturer, model) DO UPDATE SET
    "formFactor" = EXCLUDED."formFactor", "heightU" = EXCLUDED."heightU", "maxPowerW" = EXCLUDED."maxPowerW",
    description = EXCLUDED.description, "updatedAt" = NOW();
UPDATE "Device" SET "deviceModelId" = (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Brokkr' AND model = 'Sim Virtual Server'), "updatedAt" = NOW()
WHERE id IN ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000004');

-- DCIM rack roles + the one shared sim rack
INSERT INTO "DcimRackRole" (id, name, slug, color, "updatedAt")
VALUES ('a465eac5-f174-58fc-9c38-523cb2d07bed', 'Compute', 'compute', '#3b82f6', NOW())
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name, color = EXCLUDED.color, "updatedAt" = NOW();
INSERT INTO "DcimRackRole" (id, name, slug, color, "updatedAt")
VALUES ('69738fa8-693d-5275-b938-87de31ebac2c', 'Network', 'network', '#06b6d4', NOW())
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name, color = EXCLUDED.color, "updatedAt" = NOW();
INSERT INTO "DcimRackRole" (id, name, slug, color, "updatedAt")
VALUES ('d62acdfa-e053-50c1-9431-d64548513f65', 'Power', 'power', '#64748b', NOW())
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name, color = EXCLUDED.color, "updatedAt" = NOW();
INSERT INTO "Rack" (id, name, status, role, "heightU", "zoneId", "organizationId", description, "updatedAt")
VALUES ('35d476e5-c653-5a72-87a6-d824fc2ee286', 'SIM-R1', 'ACTIVE'::"RackStatus", 'MIXED'::"RackRole", 42,
    '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    'Simulated lab rack — every sim device mounts here', NOW())
ON CONFLICT ("zoneId", name) DO UPDATE SET
    status = EXCLUDED.status, role = EXCLUDED.role, "heightU" = EXCLUDED."heightU",
    "organizationId" = EXCLUDED."organizationId", description = EXCLUDED.description, "updatedAt" = NOW();

-- Peer infra devices (role=Baremetal + model, no MTI child rows — matches the app seed)
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('fb26b01a-15fd-5ff3-8a28-9611a46aceb6', 'sim-tor-1', 'ACTIVE'::"DeviceStatus", 'Baremetal'::"DeviceRole",
    'Baremetal'::"DeviceType", '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'NVIDIA' AND model = 'SN2201'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('fd2c9ff0-1c21-5a9b-b377-36f2922e13f0', 'sim-pdu-1', 'ACTIVE'::"DeviceStatus", 'Baremetal'::"DeviceRole",
    'Baremetal'::"DeviceType", '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Eaton' AND model = '9001-22313'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('8f1c3dfa-3d74-54aa-bf73-c771ee40a963', 'sim-conserver-1', 'ACTIVE'::"DeviceStatus", 'Baremetal'::"DeviceRole",
    'Baremetal'::"DeviceType", '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Opengear' AND model = 'IM7248'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('5a15cec4-60b5-55e9-9a3d-1cc7836fe065', 'sim-patch-1', 'ACTIVE'::"DeviceStatus", 'Baremetal'::"DeviceRole",
    'Baremetal'::"DeviceType", '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Generic' AND model = 'LC-24 Patch Panel'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();

-- PDU-role devices (Device.role=PDU + Pdu child row) for /dcim/pdus
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('5a09a894-c315-5393-8c4b-d1454e149847', 'sim-pdu-a', 'ACTIVE'::"DeviceStatus", 'PDU'::"DeviceRole", NULL,
    '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Eaton' AND model = '9001-22313'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Pdu" (id, "outletCount", "ratedAmperage", "voltageType", "powerStatus", "deviceId", "updatedAt")
VALUES ('ef16fd85-2bc7-59d5-978d-d732366d7901', 24, 30, '208V', 'On'::"PduPowerStatus",
    '5a09a894-c315-5393-8c4b-d1454e149847', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "outletCount" = EXCLUDED."outletCount", "ratedAmperage" = EXCLUDED."ratedAmperage",
    "voltageType" = EXCLUDED."voltageType", "powerStatus" = EXCLUDED."powerStatus", "updatedAt" = NOW();
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('e14c55d8-d315-5ead-93ea-e3edacc75110', 'sim-pdu-b', 'ACTIVE'::"DeviceStatus", 'PDU'::"DeviceRole", NULL,
    '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Eaton' AND model = '9001-22313'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Pdu" (id, "outletCount", "ratedAmperage", "voltageType", "powerStatus", "deviceId", "updatedAt")
VALUES ('56abbda7-4cde-5967-91fb-0a21ba53ea85', 42, 60, '415V', 'Off'::"PduPowerStatus",
    'e14c55d8-d315-5ead-93ea-e3edacc75110', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "outletCount" = EXCLUDED."outletCount", "ratedAmperage" = EXCLUDED."ratedAmperage",
    "voltageType" = EXCLUDED."voltageType", "powerStatus" = EXCLUDED."powerStatus", "updatedAt" = NOW();

-- CDU-role devices (Device.role=CDU + Cdu child row) for /dcim/cdus
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('ceef5664-0ca6-58fe-851b-24e0b4b37ae0', 'sim-cdu-a', 'ACTIVE'::"DeviceStatus", 'CDU'::"DeviceRole", NULL,
    '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Motivair' AND model = 'ChilledDoor CDU-40'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Cdu" (id, "coolantType", "ratedFlowRateLpm", "ratedThermalCapacityKw", airflow, "powerStatus", "deviceId",
    "updatedAt")
VALUES ('956ab600-e6ed-5bcc-b606-0ace8ce2ff88', 'water', 120.0, 300, 'FrontToRear'::"Airflow", 'On'::"CduPowerStatus",
    'ceef5664-0ca6-58fe-851b-24e0b4b37ae0', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "coolantType" = EXCLUDED."coolantType", "ratedFlowRateLpm" = EXCLUDED."ratedFlowRateLpm",
    "ratedThermalCapacityKw" = EXCLUDED."ratedThermalCapacityKw", airflow = EXCLUDED.airflow,
    "powerStatus" = EXCLUDED."powerStatus", "updatedAt" = NOW();
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('601b818c-7c33-5cce-a350-1da3d5b9cef6', 'sim-cdu-b', 'ACTIVE'::"DeviceStatus", 'CDU'::"DeviceRole", NULL,
    '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Motivair' AND model = 'ChilledDoor CDU-40'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Cdu" (id, "coolantType", "ratedFlowRateLpm", "ratedThermalCapacityKw", airflow, "powerStatus", "deviceId",
    "updatedAt")
VALUES ('355ed3e9-8ae5-5219-b750-086595716caf', 'glycol', 90.5, 200, 'RearToFront'::"Airflow", 'Off'::"CduPowerStatus",
    '601b818c-7c33-5cce-a350-1da3d5b9cef6', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "coolantType" = EXCLUDED."coolantType", "ratedFlowRateLpm" = EXCLUDED."ratedFlowRateLpm",
    "ratedThermalCapacityKw" = EXCLUDED."ratedThermalCapacityKw", airflow = EXCLUDED.airflow,
    "powerStatus" = EXCLUDED."powerStatus", "updatedAt" = NOW();

-- Switch-role devices (Device.role=Switch + Switch child row) for /dcim/switches
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('a3cfdbc7-d9ef-5056-ad9d-f88b698cafd9', 'sim-switch-a', 'ACTIVE'::"DeviceStatus", 'Switch'::"DeviceRole", NULL,
    '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'NVIDIA' AND model = 'SN2201'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Switch" (id, "switchRole", fabric, "portCount", "powerStatus", "deviceId", "updatedAt")
VALUES ('5da466ab-fafd-58a8-bb2e-0606c4b9450f', 'leaf', 'east-west', 48, 'On'::"SwitchPowerStatus",
    'a3cfdbc7-d9ef-5056-ad9d-f88b698cafd9', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "switchRole" = EXCLUDED."switchRole", fabric = EXCLUDED.fabric, "portCount" = EXCLUDED."portCount",
    "powerStatus" = EXCLUDED."powerStatus", "updatedAt" = NOW();
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('9491f4dd-8703-5164-a227-feb9cce8bc93', 'sim-switch-b', 'ACTIVE'::"DeviceStatus", 'Switch'::"DeviceRole", NULL,
    '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'NVIDIA' AND model = 'SN2201'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Switch" (id, "switchRole", fabric, "portCount", "powerStatus", "deviceId", "updatedAt")
VALUES ('d1308a88-7ed0-5ce5-89c9-d9b20b3a8f46', 'spine', 'north-south', 48, 'Off'::"SwitchPowerStatus",
    '9491f4dd-8703-5164-a227-feb9cce8bc93', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "switchRole" = EXCLUDED."switchRole", fabric = EXCLUDED.fabric, "portCount" = EXCLUDED."portCount",
    "powerStatus" = EXCLUDED."powerStatus", "updatedAt" = NOW();

-- Router-role devices (Device.role=Router + Router child row) for /dcim/routers
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('cab79d2d-80b7-5d32-a2bf-7ebcbd80b45b', 'sim-router-a', 'ACTIVE'::"DeviceStatus", 'Router'::"DeviceRole", NULL,
    '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Juniper' AND model = 'MX204'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Router" (id, "routerType", "bgpAsn", "powerStatus", "deviceId", "updatedAt")
VALUES ('c5f65149-5ad0-5741-8f76-701387fe5908', 'edge', 64512, 'On'::"RouterPowerStatus",
    'cab79d2d-80b7-5d32-a2bf-7ebcbd80b45b', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "routerType" = EXCLUDED."routerType", "bgpAsn" = EXCLUDED."bgpAsn", "powerStatus" = EXCLUDED."powerStatus",
    "updatedAt" = NOW();
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('42b758ac-a9bc-5a35-827d-234b927fb44e', 'sim-router-b', 'ACTIVE'::"DeviceStatus", 'Router'::"DeviceRole", NULL,
    '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Juniper' AND model = 'MX204'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "Router" (id, "routerType", "bgpAsn", "powerStatus", "deviceId", "updatedAt")
VALUES ('c91640a9-e092-5fd3-b6cf-5acfee21eb44', 'border', 64513, 'Off'::"RouterPowerStatus",
    '42b758ac-a9bc-5a35-827d-234b927fb44e', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "routerType" = EXCLUDED."routerType", "bgpAsn" = EXCLUDED."bgpAsn", "powerStatus" = EXCLUDED."powerStatus",
    "updatedAt" = NOW();

-- RackBrush-role devices (Device.role=RackBrush + RackBrush child row) for /dcim/rack-brushes
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('ade8cc7a-f9ea-5a0a-9ef8-11db65ccae17', 'sim-rackbrush-a', 'ACTIVE'::"DeviceStatus", 'RackBrush'::"DeviceRole",
    NULL, '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Generic' AND model = '1U Cable Brush Panel'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "RackBrush" (id, "brushMaterial", "rackUnitHeight", "deviceId", "updatedAt")
VALUES ('df420c37-478c-5651-807c-89d4b43f3a67', 'nylon', 1, 'ade8cc7a-f9ea-5a0a-9ef8-11db65ccae17', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "brushMaterial" = EXCLUDED."brushMaterial", "rackUnitHeight" = EXCLUDED."rackUnitHeight", "updatedAt" = NOW();
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('dadbb27b-5782-5ba9-8453-7802aa9416fc', 'sim-rackbrush-b', 'ACTIVE'::"DeviceStatus", 'RackBrush'::"DeviceRole",
    NULL, '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Generic' AND model = '1U Cable Brush Panel'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "RackBrush" (id, "brushMaterial", "rackUnitHeight", "deviceId", "updatedAt")
VALUES ('2b08d1fc-0e9f-5ac0-a308-7dce54b056d3', 'polypropylene', 1, 'dadbb27b-5782-5ba9-8453-7802aa9416fc', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "brushMaterial" = EXCLUDED."brushMaterial", "rackUnitHeight" = EXCLUDED."rackUnitHeight", "updatedAt" = NOW();

-- PatchPanel-role devices (Device.role=PatchPanel + PatchPanel child row) for /dcim/patch-panels
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('09bca92e-2c77-5e19-8b1a-e8a7048ff6af', 'sim-patchpanel-a', 'ACTIVE'::"DeviceStatus",
    'PatchPanel'::"DeviceRole", NULL, '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Generic' AND model = 'LC-24 Patch Panel'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "PatchPanel" (id, "panelType", "portCount", "rackUnitHeight", "deviceId", "updatedAt")
VALUES ('c8b83fa6-5126-503f-b618-c4478963938f', 'fiber', 24, 1, '09bca92e-2c77-5e19-8b1a-e8a7048ff6af', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "panelType" = EXCLUDED."panelType", "portCount" = EXCLUDED."portCount",
    "rackUnitHeight" = EXCLUDED."rackUnitHeight", "updatedAt" = NOW();
INSERT INTO "Device" (id, name, status, role, "deviceType", "zoneId", "supplierId", "organizationId", "deviceModelId",
    "updatedAt")
VALUES ('326bd015-4689-53af-942d-2643572828b8', 'sim-patchpanel-b', 'ACTIVE'::"DeviceStatus",
    'PatchPanel'::"DeviceRole", NULL, '00000000-0000-0000-0000-111111111111', '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000000',
    (SELECT id FROM "DeviceModel" WHERE manufacturer = 'Generic' AND model = 'Cat6A-48 Patch Panel'), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, role = EXCLUDED.role, "zoneId" = EXCLUDED."zoneId", "supplierId" = EXCLUDED."supplierId",
    "organizationId" = EXCLUDED."organizationId", "deviceModelId" = EXCLUDED."deviceModelId", "updatedAt" = NOW();
INSERT INTO "PatchPanel" (id, "panelType", "portCount", "rackUnitHeight", "deviceId", "updatedAt")
VALUES ('9fd5c265-aafe-5183-af45-4e867b2c6199', 'copper', 48, 1, '326bd015-4689-53af-942d-2643572828b8', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    "panelType" = EXCLUDED."panelType", "portCount" = EXCLUDED."portCount",
    "rackUnitHeight" = EXCLUDED."rackUnitHeight", "updatedAt" = NOW();

-- Rack elevation
INSERT INTO "DeviceRackAssignment" (id, position, face, "heightU", "deviceId", "rackId", "updatedAt")
VALUES ('bd1cfc75-ecb5-5413-b777-206f95ba7c2f', 1, 'FRONT'::"RackFace", 2, '00000000-0000-0000-0000-000000000001',
    '35d476e5-c653-5a72-87a6-d824fc2ee286', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    position = EXCLUDED.position, face = EXCLUDED.face, "heightU" = EXCLUDED."heightU", "rackId" = EXCLUDED."rackId",
    "updatedAt" = NOW();
INSERT INTO "DeviceRackAssignment" (id, position, face, "heightU", "deviceId", "rackId", "updatedAt")
VALUES ('c481a6c3-1ae6-5fe8-a9d2-a4848bab76b3', 3, 'FRONT'::"RackFace", 2, '00000000-0000-0000-0000-000000000002',
    '35d476e5-c653-5a72-87a6-d824fc2ee286', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    position = EXCLUDED.position, face = EXCLUDED.face, "heightU" = EXCLUDED."heightU", "rackId" = EXCLUDED."rackId",
    "updatedAt" = NOW();
INSERT INTO "DeviceRackAssignment" (id, position, face, "heightU", "deviceId", "rackId", "updatedAt")
VALUES ('98cd5cfc-d574-519e-b128-6f72d82beee3', 7, 'FRONT'::"RackFace", 2, '00000000-0000-0000-0000-000000000004',
    '35d476e5-c653-5a72-87a6-d824fc2ee286', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    position = EXCLUDED.position, face = EXCLUDED.face, "heightU" = EXCLUDED."heightU", "rackId" = EXCLUDED."rackId",
    "updatedAt" = NOW();
INSERT INTO "DeviceRackAssignment" (id, position, face, "heightU", "deviceId", "rackId", "updatedAt")
VALUES ('28908009-9d90-508e-8438-e8b2d2a53d90', 42, 'REAR'::"RackFace", 1, 'fd2c9ff0-1c21-5a9b-b377-36f2922e13f0',
    '35d476e5-c653-5a72-87a6-d824fc2ee286', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    position = EXCLUDED.position, face = EXCLUDED.face, "heightU" = EXCLUDED."heightU", "rackId" = EXCLUDED."rackId",
    "updatedAt" = NOW();
INSERT INTO "DeviceRackAssignment" (id, position, face, "heightU", "deviceId", "rackId", "updatedAt")
VALUES ('b6bd49d6-351f-5876-a0af-3089b570c49d', 41, 'REAR'::"RackFace", 1, 'fb26b01a-15fd-5ff3-8a28-9611a46aceb6',
    '35d476e5-c653-5a72-87a6-d824fc2ee286', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    position = EXCLUDED.position, face = EXCLUDED.face, "heightU" = EXCLUDED."heightU", "rackId" = EXCLUDED."rackId",
    "updatedAt" = NOW();
INSERT INTO "DeviceRackAssignment" (id, position, face, "heightU", "deviceId", "rackId", "updatedAt")
VALUES ('8cd8e3bb-cc49-5123-9120-8b93f66750f2', 40, 'REAR'::"RackFace", 1, '8f1c3dfa-3d74-54aa-bf73-c771ee40a963',
    '35d476e5-c653-5a72-87a6-d824fc2ee286', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    position = EXCLUDED.position, face = EXCLUDED.face, "heightU" = EXCLUDED."heightU", "rackId" = EXCLUDED."rackId",
    "updatedAt" = NOW();
INSERT INTO "DeviceRackAssignment" (id, position, face, "heightU", "deviceId", "rackId", "updatedAt")
VALUES ('f6455976-5041-58c0-b408-e4af22ced271', 39, 'REAR'::"RackFace", 1, '5a15cec4-60b5-55e9-9a3d-1cc7836fe065',
    '35d476e5-c653-5a72-87a6-d824fc2ee286', NOW())
ON CONFLICT ("deviceId") DO UPDATE SET
    position = EXCLUDED.position, face = EXCLUDED.face, "heightU" = EXCLUDED."heightU", "rackId" = EXCLUDED."rackId",
    "updatedAt" = NOW();

-- Server console + power ports
INSERT INTO "ConsolePort" (id, name, type, speed, "deviceId", "updatedAt")
VALUES ('4c756f56-f831-50e0-9f30-1c5a0865e3ac', 'Console', 'RJ45'::"ConsolePortType", 115200,
    '00000000-0000-0000-0000-000000000001', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "PowerPort" (id, name, type, "maximumDraw", "allocatedDraw", "deviceId", "updatedAt")
VALUES ('dcb11d37-0d82-56ea-8f09-a817c3782a66', 'PSU1', 'IEC_C14'::"PowerPortType", 800, 400,
    '00000000-0000-0000-0000-000000000001', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, "maximumDraw" = EXCLUDED."maximumDraw", "allocatedDraw" = EXCLUDED."allocatedDraw",
    "updatedAt" = NOW();
INSERT INTO "ConsolePort" (id, name, type, speed, "deviceId", "updatedAt")
VALUES ('0ceef1bd-d6aa-5467-aa04-2c15c7caf721', 'Console', 'RJ45'::"ConsolePortType", 115200,
    '00000000-0000-0000-0000-000000000002', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "PowerPort" (id, name, type, "maximumDraw", "allocatedDraw", "deviceId", "updatedAt")
VALUES ('c26021dc-3acc-50f4-ae2f-bd89e0584e5e', 'PSU1', 'IEC_C14'::"PowerPortType", 800, 400,
    '00000000-0000-0000-0000-000000000002', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, "maximumDraw" = EXCLUDED."maximumDraw", "allocatedDraw" = EXCLUDED."allocatedDraw",
    "updatedAt" = NOW();
INSERT INTO "ConsolePort" (id, name, type, speed, "deviceId", "updatedAt")
VALUES ('6eb6f6fa-081e-5dd8-be16-e67919f7e9c5', 'Console', 'RJ45'::"ConsolePortType", 115200,
    '00000000-0000-0000-0000-000000000004', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "PowerPort" (id, name, type, "maximumDraw", "allocatedDraw", "deviceId", "updatedAt")
VALUES ('03ab04a1-c44c-54d4-b0fa-e9a3ed2cd694', 'PSU1', 'IEC_C14'::"PowerPortType", 800, 400,
    '00000000-0000-0000-0000-000000000004', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, "maximumDraw" = EXCLUDED."maximumDraw", "allocatedDraw" = EXCLUDED."allocatedDraw",
    "updatedAt" = NOW();

-- Switch interfaces (mgmt0 + swp1..swp4 + swp47/swp48)
INSERT INTO "Interface" (id, name, type, enabled, "mgmtOnly", speed, "deviceId", "updatedAt")
VALUES ('38c3dae9-4826-597a-9a14-7e163f5d6dde', 'mgmt0', 'ETHERNET_1G'::"InterfaceType", true, true, 1000,
    'fb26b01a-15fd-5ff3-8a28-9611a46aceb6', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "mgmtOnly" = EXCLUDED."mgmtOnly", speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "Interface" (id, name, type, enabled, "mgmtOnly", speed, "deviceId", "updatedAt")
VALUES ('13a0863e-ca41-5b6b-93d7-645444c33cae', 'swp1', 'ETHERNET_25G'::"InterfaceType", true, false, 25000,
    'fb26b01a-15fd-5ff3-8a28-9611a46aceb6', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "mgmtOnly" = EXCLUDED."mgmtOnly", speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "Interface" (id, name, type, enabled, "mgmtOnly", speed, "deviceId", "updatedAt")
VALUES ('e3be8a6b-2e27-5a0b-a5ba-d8c692be60c8', 'swp2', 'ETHERNET_25G'::"InterfaceType", true, false, 25000,
    'fb26b01a-15fd-5ff3-8a28-9611a46aceb6', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "mgmtOnly" = EXCLUDED."mgmtOnly", speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "Interface" (id, name, type, enabled, "mgmtOnly", speed, "deviceId", "updatedAt")
VALUES ('50a53190-f25c-518a-8ebd-7614c617104c', 'swp3', 'ETHERNET_25G'::"InterfaceType", true, false, 25000,
    'fb26b01a-15fd-5ff3-8a28-9611a46aceb6', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "mgmtOnly" = EXCLUDED."mgmtOnly", speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "Interface" (id, name, type, enabled, "mgmtOnly", speed, "deviceId", "updatedAt")
VALUES ('11f7a7ae-e4f7-5178-9d0b-c04da8504160', 'swp4', 'ETHERNET_25G'::"InterfaceType", true, false, 25000,
    'fb26b01a-15fd-5ff3-8a28-9611a46aceb6', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "mgmtOnly" = EXCLUDED."mgmtOnly", speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "Interface" (id, name, type, enabled, "mgmtOnly", speed, "deviceId", "updatedAt")
VALUES ('7f03778e-eb03-50e5-9cd1-6c01fddc54c3', 'swp47', 'ETHERNET_25G'::"InterfaceType", true, false, 25000,
    'fb26b01a-15fd-5ff3-8a28-9611a46aceb6', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "mgmtOnly" = EXCLUDED."mgmtOnly", speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "Interface" (id, name, type, enabled, "mgmtOnly", speed, "deviceId", "updatedAt")
VALUES ('8f687429-85af-50fe-949c-b00cb151ee90', 'swp48', 'ETHERNET_25G'::"InterfaceType", true, false, 25000,
    'fb26b01a-15fd-5ff3-8a28-9611a46aceb6', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "mgmtOnly" = EXCLUDED."mgmtOnly", speed = EXCLUDED.speed, "updatedAt" = NOW();

-- PDU input port + outlets
INSERT INTO "PowerPort" (id, name, type, "maximumDraw", "allocatedDraw", "deviceId", "updatedAt")
VALUES ('bcf30f3e-fc2b-50c4-b1f2-f0b32f152dde', 'INPUT', 'IEC_C20'::"PowerPortType", 17000, 0,
    'fd2c9ff0-1c21-5a9b-b377-36f2922e13f0', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, "maximumDraw" = EXCLUDED."maximumDraw", "allocatedDraw" = EXCLUDED."allocatedDraw",
    "updatedAt" = NOW();
INSERT INTO "PowerOutlet" (id, name, type, "feedLegPhase", "deviceId", "updatedAt")
VALUES ('823bffd5-de2b-5b3d-b7fc-4a493224065f', 'Outlet-1', 'IEC_C13'::"PowerOutletType", 'A'::"FeedLegPhase",
    'fd2c9ff0-1c21-5a9b-b377-36f2922e13f0', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, "feedLegPhase" = EXCLUDED."feedLegPhase", "updatedAt" = NOW();
INSERT INTO "PowerOutlet" (id, name, type, "feedLegPhase", "deviceId", "updatedAt")
VALUES ('1e198a3d-763b-5dd4-84c2-c7b5adb25ffb', 'Outlet-2', 'IEC_C13'::"PowerOutletType", 'A'::"FeedLegPhase",
    'fd2c9ff0-1c21-5a9b-b377-36f2922e13f0', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, "feedLegPhase" = EXCLUDED."feedLegPhase", "updatedAt" = NOW();
INSERT INTO "PowerOutlet" (id, name, type, "feedLegPhase", "deviceId", "updatedAt")
VALUES ('95fcd51e-08f5-5883-8447-60654e78d4be', 'Outlet-4', 'IEC_C13'::"PowerOutletType", 'A'::"FeedLegPhase",
    'fd2c9ff0-1c21-5a9b-b377-36f2922e13f0', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, "feedLegPhase" = EXCLUDED."feedLegPhase", "updatedAt" = NOW();

-- Console-server mgmt + aggregator ports
INSERT INTO "Interface" (id, name, type, enabled, "mgmtOnly", speed, "deviceId", "updatedAt")
VALUES ('9d207c04-00a8-54d2-b441-fdbe189aafd0', 'mgmt0', 'ETHERNET_1G'::"InterfaceType", true, true, 1000,
    '8f1c3dfa-3d74-54aa-bf73-c771ee40a963', NOW())
ON CONFLICT ("deviceId", name) WHERE "deletedAt" IS NULL DO UPDATE SET
    type = EXCLUDED.type, "mgmtOnly" = EXCLUDED."mgmtOnly", speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "ConsoleServerPort" (id, name, type, speed, "deviceId", "updatedAt")
VALUES ('30c52934-d945-5e85-a477-cffe37368480', 'port-01', 'RJ45'::"ConsolePortType", 9600,
    '8f1c3dfa-3d74-54aa-bf73-c771ee40a963', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "ConsoleServerPort" (id, name, type, speed, "deviceId", "updatedAt")
VALUES ('5ef175ff-e2f2-5fba-a0bf-672114330bf0', 'port-02', 'RJ45'::"ConsolePortType", 9600,
    '8f1c3dfa-3d74-54aa-bf73-c771ee40a963', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, speed = EXCLUDED.speed, "updatedAt" = NOW();
INSERT INTO "ConsoleServerPort" (id, name, type, speed, "deviceId", "updatedAt")
VALUES ('0c300e69-662a-56ec-8788-a7a4252fb217', 'port-04', 'RJ45'::"ConsolePortType", 9600,
    '8f1c3dfa-3d74-54aa-bf73-c771ee40a963', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, speed = EXCLUDED.speed, "updatedAt" = NOW();

-- Patch-panel rear + front ports
INSERT INTO "RearPort" (id, name, type, positions, "deviceId", "updatedAt")
VALUES ('2d9ef871-3266-5212-9b30-7fb62239eec3', 'RP-01', 'LC'::"PortType", 1, '5a15cec4-60b5-55e9-9a3d-1cc7836fe065',
    NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, positions = EXCLUDED.positions, "updatedAt" = NOW();
INSERT INTO "FrontPort" (id, name, type, "rearPortId", "rearPortPosition", "deviceId", "updatedAt")
VALUES ('0d849b9d-4630-5382-96d6-f5469bcedf2d', 'FP-01', 'LC'::"PortType", '2d9ef871-3266-5212-9b30-7fb62239eec3', 1,
    '5a15cec4-60b5-55e9-9a3d-1cc7836fe065', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, "rearPortId" = EXCLUDED."rearPortId", "updatedAt" = NOW();
INSERT INTO "RearPort" (id, name, type, positions, "deviceId", "updatedAt")
VALUES ('1da03516-5e5d-57c6-96a1-edaf0918c30c', 'RP-02', 'LC'::"PortType", 1, '5a15cec4-60b5-55e9-9a3d-1cc7836fe065',
    NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, positions = EXCLUDED.positions, "updatedAt" = NOW();
INSERT INTO "FrontPort" (id, name, type, "rearPortId", "rearPortPosition", "deviceId", "updatedAt")
VALUES ('355a2665-8620-528e-9ce2-d350d8155a56', 'FP-02', 'LC'::"PortType", '1da03516-5e5d-57c6-96a1-edaf0918c30c', 1,
    '5a15cec4-60b5-55e9-9a3d-1cc7836fe065', NOW())
ON CONFLICT ("deviceId", name) DO UPDATE SET
    type = EXCLUDED.type, "rearPortId" = EXCLUDED."rearPortId", "updatedAt" = NOW();

-- Cables
DELETE FROM "Cable" c
WHERE c.id NOT IN ('83015101-4204-52be-9fc8-cbf28596a4ae', 'ad01f9cd-f9be-5f34-a229-dfb1a859633d',
    '990730aa-45f5-5574-9033-6764153bb81c', 'e1b18c50-c16a-55cf-82e6-f257070c8edf',
    '89d6b2a5-5f8b-547c-8d69-6289b40e0df4', '25878bb1-612e-5d46-b505-184a692ca996',
    '3d34c750-bb37-5f48-a5cf-3f5c4321ab98', '1d76dbb6-25ec-5bfd-82ad-4f45c224acc2',
    '61210ba9-0a33-5bb4-8af4-abe4baa044c5', 'da1eee97-d353-58ab-b69b-4f1619296808',
    'cb0f23f6-b402-5c17-ba0b-88a71e0766b8')
    AND EXISTS (
        SELECT 1 FROM "CableTermination" ct
        JOIN "Interface" i ON i.id = ct."terminationId"
        WHERE ct."cableId" = c.id
            AND ct."terminationType" = 'INTERFACE'::"CableTerminationType"
            AND i."deviceId" = 'fb26b01a-15fd-5ff3-8a28-9611a46aceb6'
    );
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('83015101-4204-52be-9fc8-cbf28596a4ae', 'DAC'::"CableType", 'CONNECTED'::"CableStatus",
    'cpu-1 eth0 → sim-tor-1 swp1', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('d5f5a550-a08c-5467-9cb2-a535d3e51ef4', 'A'::"CableSide", 'INTERFACE'::"CableTerminationType",
    (SELECT id FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000001' AND name = 'eth0' AND "deletedAt" IS NULL),
    '83015101-4204-52be-9fc8-cbf28596a4ae')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('d35644df-6c48-5fee-b7ea-5f869b327bf6', 'B'::"CableSide", 'INTERFACE'::"CableTerminationType",
    '13a0863e-ca41-5b6b-93d7-645444c33cae', '83015101-4204-52be-9fc8-cbf28596a4ae')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('ad01f9cd-f9be-5f34-a229-dfb1a859633d', 'POWER'::"CableType", 'CONNECTED'::"CableStatus",
    'cpu-1 PSU1 → sim-pdu-1 Outlet-1', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('b48fdb19-807f-5a81-915a-1fc17dedba57', 'A'::"CableSide", 'POWER_PORT'::"CableTerminationType",
    'dcb11d37-0d82-56ea-8f09-a817c3782a66', 'ad01f9cd-f9be-5f34-a229-dfb1a859633d')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('5603358a-8776-54b9-a996-390415801087', 'B'::"CableSide", 'POWER_OUTLET'::"CableTerminationType",
    '823bffd5-de2b-5b3d-b7fc-4a493224065f', 'ad01f9cd-f9be-5f34-a229-dfb1a859633d')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('990730aa-45f5-5574-9033-6764153bb81c', 'SERIAL'::"CableType", 'CONNECTED'::"CableStatus",
    'cpu-1 Console → sim-conserver-1 port-01', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('59d837c2-abb3-5aaf-94fb-cf742dce2980', 'A'::"CableSide", 'CONSOLE_PORT'::"CableTerminationType",
    '4c756f56-f831-50e0-9f30-1c5a0865e3ac', '990730aa-45f5-5574-9033-6764153bb81c')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('7497da1d-02af-5981-8d76-d5ca2ba20731', 'B'::"CableSide", 'CONSOLE_SERVER_PORT'::"CableTerminationType",
    '30c52934-d945-5e85-a477-cffe37368480', '990730aa-45f5-5574-9033-6764153bb81c')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('e1b18c50-c16a-55cf-82e6-f257070c8edf', 'DAC'::"CableType", 'CONNECTED'::"CableStatus",
    'cpu-2 eth0 → sim-tor-1 swp2', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('81b7e378-bf5f-57bd-b97a-323380df58b9', 'A'::"CableSide", 'INTERFACE'::"CableTerminationType",
    (SELECT id FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000002' AND name = 'eth0' AND "deletedAt" IS NULL),
    'e1b18c50-c16a-55cf-82e6-f257070c8edf')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('34a82cbb-b3e6-5fff-ba14-3a74a8c11e65', 'B'::"CableSide", 'INTERFACE'::"CableTerminationType",
    'e3be8a6b-2e27-5a0b-a5ba-d8c692be60c8', 'e1b18c50-c16a-55cf-82e6-f257070c8edf')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('89d6b2a5-5f8b-547c-8d69-6289b40e0df4', 'POWER'::"CableType", 'CONNECTED'::"CableStatus",
    'cpu-2 PSU1 → sim-pdu-1 Outlet-2', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('89d0ceb3-3ad6-5488-b481-ac08c48fa515', 'A'::"CableSide", 'POWER_PORT'::"CableTerminationType",
    'c26021dc-3acc-50f4-ae2f-bd89e0584e5e', '89d6b2a5-5f8b-547c-8d69-6289b40e0df4')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('3664d05c-2d33-5a72-a250-58f3d26004d1', 'B'::"CableSide", 'POWER_OUTLET'::"CableTerminationType",
    '1e198a3d-763b-5dd4-84c2-c7b5adb25ffb', '89d6b2a5-5f8b-547c-8d69-6289b40e0df4')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('25878bb1-612e-5d46-b505-184a692ca996', 'SERIAL'::"CableType", 'CONNECTED'::"CableStatus",
    'cpu-2 Console → sim-conserver-1 port-02', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('71208472-c5e9-529d-ac5f-343b896de99b', 'A'::"CableSide", 'CONSOLE_PORT'::"CableTerminationType",
    '0ceef1bd-d6aa-5467-aa04-2c15c7caf721', '25878bb1-612e-5d46-b505-184a692ca996')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('ed66ebcb-e1b7-5818-8ffd-90ace999c6f0', 'B'::"CableSide", 'CONSOLE_SERVER_PORT'::"CableTerminationType",
    '5ef175ff-e2f2-5fba-a0bf-672114330bf0', '25878bb1-612e-5d46-b505-184a692ca996')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('3d34c750-bb37-5f48-a5cf-3f5c4321ab98', 'DAC'::"CableType", 'CONNECTED'::"CableStatus",
    'cpu-4 eth0 → sim-tor-1 swp4', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('0ffbd986-ac6c-5f62-b0d7-0e1c530cdfb4', 'A'::"CableSide", 'INTERFACE'::"CableTerminationType",
    (SELECT id FROM "Interface" WHERE "deviceId" = '00000000-0000-0000-0000-000000000004' AND name = 'eth0' AND "deletedAt" IS NULL),
    '3d34c750-bb37-5f48-a5cf-3f5c4321ab98')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('9d3f788a-18b0-5247-b299-f6ee5706cbbf', 'B'::"CableSide", 'INTERFACE'::"CableTerminationType",
    '11f7a7ae-e4f7-5178-9d0b-c04da8504160', '3d34c750-bb37-5f48-a5cf-3f5c4321ab98')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('1d76dbb6-25ec-5bfd-82ad-4f45c224acc2', 'POWER'::"CableType", 'CONNECTED'::"CableStatus",
    'cpu-4 PSU1 → sim-pdu-1 Outlet-4', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('4a7625af-c8eb-5515-9dbd-4380634f835e', 'A'::"CableSide", 'POWER_PORT'::"CableTerminationType",
    '03ab04a1-c44c-54d4-b0fa-e9a3ed2cd694', '1d76dbb6-25ec-5bfd-82ad-4f45c224acc2')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('7cc83da3-21c8-5ae1-bf41-bd90fb8bb47b', 'B'::"CableSide", 'POWER_OUTLET'::"CableTerminationType",
    '95fcd51e-08f5-5883-8447-60654e78d4be', '1d76dbb6-25ec-5bfd-82ad-4f45c224acc2')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('61210ba9-0a33-5bb4-8af4-abe4baa044c5', 'SERIAL'::"CableType", 'CONNECTED'::"CableStatus",
    'cpu-4 Console → sim-conserver-1 port-04', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('f6a63d43-d384-5fe5-bd27-bfb8b7d708dc', 'A'::"CableSide", 'CONSOLE_PORT'::"CableTerminationType",
    '6eb6f6fa-081e-5dd8-be16-e67919f7e9c5', '61210ba9-0a33-5bb4-8af4-abe4baa044c5')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('5d3b0947-0b38-5ca3-b22c-fd7c1771125d', 'B'::"CableSide", 'CONSOLE_SERVER_PORT'::"CableTerminationType",
    '0c300e69-662a-56ec-8788-a7a4252fb217', '61210ba9-0a33-5bb4-8af4-abe4baa044c5')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('da1eee97-d353-58ab-b69b-4f1619296808', 'SMF_OS2'::"CableType", 'CONNECTED'::"CableStatus",
    'sim-patch-1 FP-01 → sim-tor-1 swp47', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('fa8463c1-0d43-518d-8f08-933bd42d6b4a', 'A'::"CableSide", 'FRONT_PORT'::"CableTerminationType",
    '0d849b9d-4630-5382-96d6-f5469bcedf2d', 'da1eee97-d353-58ab-b69b-4f1619296808')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('b7c15c9f-f142-58b1-b67b-6a9d07c014e4', 'B'::"CableSide", 'INTERFACE'::"CableTerminationType",
    '7f03778e-eb03-50e5-9cd1-6c01fddc54c3', 'da1eee97-d353-58ab-b69b-4f1619296808')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "Cable" (id, type, status, label, "updatedAt")
VALUES ('cb0f23f6-b402-5c17-ba0b-88a71e0766b8', 'SMF_OS2'::"CableType", 'CONNECTED'::"CableStatus",
    'sim-patch-1 RP-02 → sim-tor-1 swp48', NOW())
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, status = EXCLUDED.status, label = EXCLUDED.label, "updatedAt" = NOW();
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('e7fd1d0c-8576-517a-8721-f9031e7b1374', 'A'::"CableSide", 'REAR_PORT'::"CableTerminationType",
    '1da03516-5e5d-57c6-96a1-edaf0918c30c', 'cb0f23f6-b402-5c17-ba0b-88a71e0766b8')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";
INSERT INTO "CableTermination" (id, "cableSide", "terminationType", "terminationId", "cableId")
VALUES ('4d9cb33c-937c-56f6-8b17-8d291076b31c', 'B'::"CableSide", 'INTERFACE'::"CableTerminationType",
    '8f687429-85af-50fe-949c-b00cb151ee90', 'cb0f23f6-b402-5c17-ba0b-88a71e0766b8')
ON CONFLICT ("cableId", "cableSide") DO UPDATE SET
    "terminationType" = EXCLUDED."terminationType", "terminationId" = EXCLUDED."terminationId";

-- Tags + assignments
INSERT INTO "Tag" (id, name, slug, color, "organizationId", "updatedAt")
VALUES ('5d70e550-0b71-5f50-806a-008498ca21dd', 'Compute', 'compute', '#3b82f6', '00000000-0000-0000-0000-000000000000',
    NOW())
ON CONFLICT ("organizationId", name) DO UPDATE SET
    slug = EXCLUDED.slug, color = EXCLUDED.color, "updatedAt" = NOW();
INSERT INTO "Tag" (id, name, slug, color, "organizationId", "updatedAt")
VALUES ('0a578a9e-422f-546c-aa65-f340c2586e62', 'Managed', 'managed', '#10b981', '00000000-0000-0000-0000-000000000000',
    NOW())
ON CONFLICT ("organizationId", name) DO UPDATE SET
    slug = EXCLUDED.slug, color = EXCLUDED.color, "updatedAt" = NOW();
INSERT INTO "Tag" (id, name, slug, color, "organizationId", "updatedAt")
VALUES ('767399f8-a156-5729-b259-a6bae918775d', 'Networking', 'networking', '#06b6d4',
    '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT ("organizationId", name) DO UPDATE SET
    slug = EXCLUDED.slug, color = EXCLUDED.color, "updatedAt" = NOW();
INSERT INTO "Tag" (id, name, slug, color, "organizationId", "updatedAt")
VALUES ('20500c03-b84a-539b-a76c-ea0875d486b2', 'Power', 'power', '#64748b', '00000000-0000-0000-0000-000000000000',
    NOW())
ON CONFLICT ("organizationId", name) DO UPDATE SET
    slug = EXCLUDED.slug, color = EXCLUDED.color, "updatedAt" = NOW();
INSERT INTO "Tag" (id, name, slug, color, "organizationId", "updatedAt")
VALUES ('acc0b210-4df9-5d03-abcd-6fadca64c2b5', 'OOB', 'oob', '#78716c', '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT ("organizationId", name) DO UPDATE SET
    slug = EXCLUDED.slug, color = EXCLUDED.color, "updatedAt" = NOW();
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('5d70e550-0b71-5f50-806a-008498ca21dd', 'DEVICE'::"TagObjectType", '00000000-0000-0000-0000-000000000001')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('0a578a9e-422f-546c-aa65-f340c2586e62', 'DEVICE'::"TagObjectType", '00000000-0000-0000-0000-000000000001')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('5d70e550-0b71-5f50-806a-008498ca21dd', 'DEVICE'::"TagObjectType", '00000000-0000-0000-0000-000000000002')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('0a578a9e-422f-546c-aa65-f340c2586e62', 'DEVICE'::"TagObjectType", '00000000-0000-0000-0000-000000000002')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('5d70e550-0b71-5f50-806a-008498ca21dd', 'DEVICE'::"TagObjectType", '00000000-0000-0000-0000-000000000004')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('0a578a9e-422f-546c-aa65-f340c2586e62', 'DEVICE'::"TagObjectType", '00000000-0000-0000-0000-000000000004')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('767399f8-a156-5729-b259-a6bae918775d', 'DEVICE'::"TagObjectType", 'fb26b01a-15fd-5ff3-8a28-9611a46aceb6')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('20500c03-b84a-539b-a76c-ea0875d486b2', 'DEVICE'::"TagObjectType", 'fd2c9ff0-1c21-5a9b-b377-36f2922e13f0')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('acc0b210-4df9-5d03-abcd-6fadca64c2b5', 'DEVICE'::"TagObjectType", '8f1c3dfa-3d74-54aa-bf73-c771ee40a963')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;
INSERT INTO "TagAssignment" ("tagId", "objectType", "objectId")
VALUES ('0a578a9e-422f-546c-aa65-f340c2586e62', 'ZONE'::"TagObjectType", '00000000-0000-0000-0000-111111111111')
ON CONFLICT ("tagId", "objectType", "objectId") DO NOTHING;

-- BGP
INSERT INTO "Asn" (id, asn, description, "organizationId", "updatedAt")
VALUES ('6dc3acc2-87ed-58ae-8e11-6914c831944b', 65000, 'Brokkr sim (local)', '00000000-0000-0000-0000-000000000000',
    NOW())
ON CONFLICT (asn) DO UPDATE SET
    description = EXCLUDED.description, "organizationId" = EXCLUDED."organizationId", "updatedAt" = NOW();
INSERT INTO "Asn" (id, asn, description, "organizationId", "updatedAt")
VALUES ('7072ed1c-5df0-5028-9a82-6b8808b88a35', 64512, 'Upstream transit (remote)',
    '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT (asn) DO UPDATE SET
    description = EXCLUDED.description, "organizationId" = EXCLUDED."organizationId", "updatedAt" = NOW();
INSERT INTO "BgpPeerGroup" (id, name, description, "organizationId", "updatedAt")
VALUES ('147b2579-f36e-51c2-989a-a4300c31b646', 'transit-upstream', 'eBGP to upstream transit',
    '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "PrefixList" (id, name, description, family, "organizationId", "updatedAt")
VALUES ('caadb2a1-29c1-5377-b868-5d22e8c7fcf8', 'advertise-out', 'Prefixes advertised to transit', 'ipv4',
    '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "PrefixListRule" (id, action, prefix, sequence, "prefixListId", "updatedAt")
VALUES ('7bc6e1e5-f4b4-550e-93b7-257a20aacfe4', 'permit', '192.168.200.0/24', 10,
    'caadb2a1-29c1-5377-b868-5d22e8c7fcf8', NOW())
ON CONFLICT (id) DO UPDATE SET
    action = EXCLUDED.action, prefix = EXCLUDED.prefix, sequence = EXCLUDED.sequence, "updatedAt" = NOW();
INSERT INTO "PrefixListRule" (id, action, prefix, sequence, "prefixListId", "updatedAt")
VALUES ('ad98fec3-55aa-5ccf-8477-98825d44e14f', 'permit', '192.168.105.0/24', 20,
    'caadb2a1-29c1-5377-b868-5d22e8c7fcf8', NOW())
ON CONFLICT (id) DO UPDATE SET
    action = EXCLUDED.action, prefix = EXCLUDED.prefix, sequence = EXCLUDED.sequence, "updatedAt" = NOW();
INSERT INTO "PrefixListRule" (id, action, prefix, sequence, "prefixListId", "updatedAt")
VALUES ('94c7ad6d-32dc-5541-b2b3-d728df9d054c', 'deny', '0.0.0.0/0', 30, 'caadb2a1-29c1-5377-b868-5d22e8c7fcf8', NOW())
ON CONFLICT (id) DO UPDATE SET
    action = EXCLUDED.action, prefix = EXCLUDED.prefix, sequence = EXCLUDED.sequence, "updatedAt" = NOW();
INSERT INTO "BgpSession" (id, name, status, "deviceId", "localAsnId", "remoteAsnId", "peerGroupId", "prefixListOutId",
    "organizationId", "updatedAt")
VALUES ('8a23ee03-8ee6-5ee5-b348-6f6693ed9beb', 'tor-upstream', 'ACTIVE'::"BgpSessionStatus",
    'fb26b01a-15fd-5ff3-8a28-9611a46aceb6', '6dc3acc2-87ed-58ae-8e11-6914c831944b',
    '7072ed1c-5df0-5028-9a82-6b8808b88a35', '147b2579-f36e-51c2-989a-a4300c31b646',
    'caadb2a1-29c1-5377-b868-5d22e8c7fcf8', '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status, "deviceId" = EXCLUDED."deviceId", "localAsnId" = EXCLUDED."localAsnId",
    "remoteAsnId" = EXCLUDED."remoteAsnId", "peerGroupId" = EXCLUDED."peerGroupId",
    "prefixListOutId" = EXCLUDED."prefixListOutId", "organizationId" = EXCLUDED."organizationId", "updatedAt" = NOW();
INSERT INTO "BgpSession" (id, name, status, "deviceId", "localAsnId", "remoteAsnId", "peerGroupId", "prefixListOutId",
    "localAddressId", "organizationId", "updatedAt")
VALUES ('07f30aaa-dfec-502a-bab1-5144f7d38111', 'cpu-1-upstream', 'PLANNED'::"BgpSessionStatus",
    '00000000-0000-0000-0000-000000000001', '6dc3acc2-87ed-58ae-8e11-6914c831944b',
    '7072ed1c-5df0-5028-9a82-6b8808b88a35', '147b2579-f36e-51c2-989a-a4300c31b646',
    'caadb2a1-29c1-5377-b868-5d22e8c7fcf8',
    (SELECT a.id FROM "IpAddress" a JOIN "Interface" iface ON iface.id = a."interfaceId" WHERE iface."deviceId" = '00000000-0000-0000-0000-000000000001' AND iface.name = 'eth0' AND iface."deletedAt" IS NULL LIMIT 1),
    '00000000-0000-0000-0000-000000000000', NOW())
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status, "deviceId" = EXCLUDED."deviceId", "localAsnId" = EXCLUDED."localAsnId",
    "remoteAsnId" = EXCLUDED."remoteAsnId", "peerGroupId" = EXCLUDED."peerGroupId",
    "prefixListOutId" = EXCLUDED."prefixListOutId", "localAddressId" = EXCLUDED."localAddressId",
    "organizationId" = EXCLUDED."organizationId", "updatedAt" = NOW();

-- Circuits
INSERT INTO "Provider" (id, name, slug, description, "updatedAt")
VALUES ('2ae98a88-0761-5706-8ad6-d69a4cf780ea', 'Sim Transit Co', 'sim-transit', 'Simulated upstream transit provider',
    NOW())
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "ProviderNetwork" (id, name, description, "providerId", "updatedAt")
VALUES ('157875f8-b3b0-59e7-b608-fa24a37c14c4', 'Sim Transit Backbone', 'Provider backbone network',
    '2ae98a88-0761-5706-8ad6-d69a4cf780ea', NOW())
ON CONFLICT ("providerId", name) DO UPDATE SET
    description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "CircuitType" (id, name, slug, description, "updatedAt")
VALUES ('72862141-e2d6-5f3d-87ae-dcdf5352d350', 'Internet Transit', 'internet-transit', 'IP transit circuit', NOW())
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, "updatedAt" = NOW();
INSERT INTO "Circuit" (id, cid, status, "commitRate", "providerId", "circuitTypeId", "organizationId", description,
    "updatedAt")
VALUES ('a8bca0b7-873f-5b99-9259-6e1a263fbafe', 'SIM-XC-001', 'ACTIVE'::"CircuitStatus", 1000000,
    '2ae98a88-0761-5706-8ad6-d69a4cf780ea', '72862141-e2d6-5f3d-87ae-dcdf5352d350',
    '00000000-0000-0000-0000-000000000000', '1G IP transit into the sim zone', NOW())
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status, "commitRate" = EXCLUDED."commitRate", "updatedAt" = NOW();
INSERT INTO "CircuitTermination" (id, "termSide", "portSpeed", "upstreamSpeed", "xconnectId", "circuitId", "zoneId",
    "updatedAt")
VALUES ('d1ff22ef-af5e-5371-bc18-0035cee1d15c', 'A'::"CircuitTerminationSide", 1000000, 1000000, 'XC-SIM-001-A',
    'a8bca0b7-873f-5b99-9259-6e1a263fbafe', '00000000-0000-0000-0000-111111111111', NOW())
ON CONFLICT ("circuitId", "termSide") DO UPDATE SET
    "portSpeed" = EXCLUDED."portSpeed", "upstreamSpeed" = EXCLUDED."upstreamSpeed", "zoneId" = EXCLUDED."zoneId",
    "updatedAt" = NOW();

COMMIT;
