{
  pkgs,
  lib,
  config,
  ...
}:

# Passwordless sim sudo. A scoped NOPASSWD sudoers drop-in, generated declaratively
# (devenv `files`) and converged across platforms. Model: the privileged sim ops run as
# root through ONE Nix-built helper (brokkr-sim-priv) pinned by its exact /nix/store path;
# the helper enforces scope IN CODE (path containment under the calling user's home, IPv4
# validation, a fixed unit allowlist — see devenv/pkgs/sim-priv.sh). macOS additionally
# keeps socket_vmnet as a direct rule (a long-lived daemon launched via Popen). We never
# glob /nix/store/* — any unprivileged user can add a store path through the nix daemon, so
# a glob would let a forged binary run as root. The bare helper path is a "simple file
# name", which sudoers (and sudo-rs) define as "any arguments" — version-robust (no wildcard
# to parse) and the reason ALL argument validation lives in the helper, not here.
#
# sudo-rs note (Ubuntu 25.10+ defaults sudo → sudo-rs): sudo-rs forbids wildcards except a
# single trailing `*`, so the old per-op arg-globs (rm -rf /home/*/…, chown * /opt/brokkr,
# pkill -f *lan.conf, ipmi_sim -c * -f * -s * -n) silently failed to match → headless
# `task up` hung on a password prompt. This converged ruleset carries no such wildcards.
#
# The drop-in is named for the helper it authorises (brokkr-sim-<store hash prefix>), so
# concurrent checkouts at different revisions install ONE FILE EACH and are both authorised;
# a single fixed name meant whichever checkout ran `task up` last silently deauthorised the
# other. Multiple brokkr-sim-* files on a host is the intended steady state, not leakage —
# each still pins one exact path, so this is not a glob by another name.
#
# That only works because the rule carries NO Cmnd_Alias. Alias names are one namespace shared
# by every file in /etc/sudoers.d, so two drop-ins declaring the same alias collide: sudo keeps
# the first file it parses, discards the second, and warns on every single sudo call — the later
# checkout is silently left unauthorised. User specifications are cumulative instead, so the
# absolute paths are inlined here. Do not reintroduce an alias to shorten the line.
#
# devenv regenerates this file when the helper/socket_vmnet store paths change; the
# sudo:setup task reinstalls (one prompt) only then.
#
# Install/remove with the devenv tasks (run them yourself in a terminal):
#   devenv tasks run sudo:setup      # one prompt; passwordless sim sudo thereafter
#   devenv tasks run sudo:teardown   # revert to per-op prompts
# These deliberately do NOT auto-fire in the bring-up DAG — a sudo prompt mid `devenv up`
# (detached / headless) would hang, and the user dislikes surprise prompts.
#
# Why it kills the prompts: once installed, `sudo -n <helper> noop` succeeds, so both the CLI's
# ensure_sudo_cached() (sim/scripts/local/process_utils.py) and the control center's
# SudoService.available() short-circuit — neither `task up` nor the TTY-less lab devenv process
# ever prompts again. Those probe the helper itself, not the allowlisted /usr/bin/true, because
# a sibling checkout's drop-in also allowlists /usr/bin/true and would answer for it.

let
  simPriv = config.env.LOCAL_SIM_PRIV_BIN; # ${simPriv}/bin/brokkr-sim-priv — pinned; rotates only on a devenv update
  # /nix/store/<hash>-brokkr-sim-priv/bin/brokkr-sim-priv → <hash>'s first 12 chars. Nix hashes are
  # [0-9a-z], so the name stays a valid sudoers.d entry (no dot, no trailing ~).
  dropinName = "brokkr-sim-${builtins.substring 0 12 (baseNameOf (dirOf (dirOf simPriv)))}";
  dropin = "/etc/sudoers.d/${dropinName}";
  legacyDropin = "/etc/sudoers.d/brokkr-sim"; # pre-content-addressing, host-wide; cleaned up on teardown
  genfile = "${config.devenv.root}/.sudoers/brokkr-sim";
  darwin = pkgs.stdenv.isDarwin;

  # macOS keeps socket_vmnet as a direct rule (a Popen-launched daemon; the trailing `*` is
  # sudo-rs-valid, though macOS uses GNU sudo). On Linux every privileged op — lo aliases via
  # ip, ipmi_sim, libvirt service start, file cleanup — goes through the helper, so there are
  # no direct binary rules at all. /usr/bin/true is the probe SudoService falls back to when
  # LOCAL_SIM_PRIV_BIN is unset.
  commands = [
    simPriv
  ]
  ++ lib.optional darwin "${config.env.LOCAL_SOCKET_VMNET_BIN} --vmnet-mode=shared *"
  ++ [ "/usr/bin/true" ];

  lines = [
    "# generated by modules/sudo.nix — do not edit. remove via: devenv tasks run sudo:teardown"
    "# __USER__ is replaced with the install-time user by the sudo:setup task."
    # No global `Defaults secure_path` here: it would resolve commands for EVERY sudo this
    # user runs (it breaks e.g. `sudo darwin-rebuild`, which lives outside the pinned dirs).
    # The helper invokes system tools by absolute path itself; socket_vmnet is passed by
    # absolute store path. The bare helper path allows any arguments — scope is enforced by
    # the helper's code, not by sudoers args.
    "__USER__ ALL=(root) NOPASSWD: ${lib.concatStringsSep ", " commands}"
  ];

  content = lib.concatStringsSep "\n" lines + "\n";
in
{
  files.".sudoers/brokkr-sim".text = content;

  # The install glue lives in devenv/scripts/install-sim-sudoers.sh (single source of truth) so the
  # Taskfile verbs can run it in a foreground, terminal-attached shell — the privileged `sudo
  # install` can't prompt usably under `devenv tasks run` on Linux (no Touch-ID fallback), which is
  # why `task up` died with "sudo: 3 incorrect password attempts" on Arch. This task is the manual
  # `devenv tasks run sudo:setup` entrypoint; `task up` / `task sudo:setup` call the same script.
  tasks."sudo:setup" = {
    description = "Install scoped NOPASSWD sudoers for passwordless sim sudo (idempotent; reversible via sudo:teardown).";
    execIfModified = [ genfile ];
    exec = ''bash "${config.devenv.root}/devenv/scripts/install-sim-sudoers.sh"'';
  };

  # single source of the drop-in removal logic; the Taskfile sudo:teardown verb invokes this
  # script directly so the sudo prompt lands on the terminal. install-sim-sudoers.sh derives the
  # same hashed name from $LOCAL_SIM_PRIV_BIN, and the same host-global marker path — keep both in sync.
  # Only THIS checkout's helper is deauthorised: a sibling revision's drop-in is left alone.
  # Removing the marker is hygiene: the drop-in is gone, so the fast path's `[ -e "$dst" ]` term
  # already fails. The $DEVENV_STATE paths clean up the pre-relocation layout.
  scripts.sudo-sim-teardown = {
    description = "Remove this checkout's brokkr-sim sudoers drop-in (revert to per-op sudo prompts).";
    exec = ''
      markers="''${XDG_STATE_HOME:-$HOME/.local/state}/brokkr-local/sudoers"
      sudo rm -f "${dropin}" "${legacyDropin}" \
        && rm -f "$markers/${dropinName}.rev" "$markers/brokkr-sim.rev" \
          "$DEVENV_STATE/sudoers/${dropinName}.rev" "$DEVENV_STATE/sudoers/brokkr-sim.rev" \
        && echo "✓ removed ${dropin}; sim sudo will prompt again"
    '';
  };

  tasks."sudo:teardown" = {
    description = "Remove this checkout's brokkr-sim sudoers drop-in (revert to per-op sudo prompts).";
    exec = "sudo-sim-teardown";
  };
}
