-- AlterTable
ALTER TABLE "Zone" DROP COLUMN "dnsTcpEnabled",
ADD COLUMN     "dhcpDeclineBackoffSeconds" INTEGER NOT NULL DEFAULT 600,
ADD COLUMN     "dhcpLeaderPollMs" INTEGER NOT NULL DEFAULT 2000,
ADD COLUMN     "dhcpPruneIntervalMs" INTEGER NOT NULL DEFAULT 60000,
ADD COLUMN     "dnsPollMs" INTEGER NOT NULL DEFAULT 2000,
ADD COLUMN     "dnsUpstreamTimeoutMs" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "vrrpGarpCount" INTEGER NOT NULL DEFAULT 5;

