import { initContract } from '@ts-rest/core';
import { z } from 'zod';
import {
  BgpPeerGroupListQuerySchema,
  BgpPeerGroupSchema,
  BgpSessionListQuerySchema,
  BgpSessionSchema,
  CreateBgpPeerGroupRequestSchema,
  CreateBgpSessionRequestSchema,
  CreatePrefixListRequestSchema,
  CreatePrefixListRuleRequestSchema,
  PrefixListListQuerySchema,
  PrefixListRuleListQuerySchema,
  PrefixListRuleSchema,
  PrefixListSchema,
  UpdateBgpPeerGroupRequestSchema,
  UpdateBgpSessionRequestSchema,
  UpdatePrefixListRequestSchema,
  UpdatePrefixListRuleRequestSchema,
} from '../schemas/bgp';
import { ErrorResponseSchema } from '../schemas/responses';
import { type RouteMetadata } from './metadata';
import { authedErrorResponses } from './responses';

const c = initContract();

const IdParamSchema = z.object({
  id: z.string().uuid(),
});

export const bgpRoutes = c.router({
  listBgpPeerGroups: {
    method: 'GET',
    path: '/bgp/peer-groups',
    query: BgpPeerGroupListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(BgpPeerGroupSchema) },
    summary: 'List BGP peer groups',
    description: 'Returns a list of BGP peer groups, optionally filtered by organization.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getBgpPeerGroup: {
    method: 'GET',
    path: '/bgp/peer-groups/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: BgpPeerGroupSchema, 404: ErrorResponseSchema },
    summary: 'Get BGP peer group by ID',
    description: 'Returns a single BGP peer group by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createBgpPeerGroup: {
    method: 'POST',
    path: '/bgp/peer-groups',
    body: CreateBgpPeerGroupRequestSchema,
    responses: { ...authedErrorResponses, 201: BgpPeerGroupSchema, 400: ErrorResponseSchema },
    summary: 'Create BGP peer group',
    description: 'Creates a new BGP peer group.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateBgpPeerGroup: {
    method: 'PATCH',
    path: '/bgp/peer-groups/:id',
    pathParams: IdParamSchema,
    body: UpdateBgpPeerGroupRequestSchema,
    responses: { ...authedErrorResponses, 200: BgpPeerGroupSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
    summary: 'Update BGP peer group',
    description: 'Updates an existing BGP peer group by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteBgpPeerGroup: {
    method: 'DELETE',
    path: '/bgp/peer-groups/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: {
      ...authedErrorResponses,
      204: z.void(),
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Delete BGP peer group',
    description: 'Deletes a BGP peer group by its UUID. Fails with 409 if any BGP sessions still reference the group.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listPrefixLists: {
    method: 'GET',
    path: '/bgp/prefix-lists',
    query: PrefixListListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(PrefixListSchema) },
    summary: 'List prefix lists',
    description: 'Returns a list of prefix lists, optionally filtered by organization or address family.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getPrefixList: {
    method: 'GET',
    path: '/bgp/prefix-lists/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: PrefixListSchema, 404: ErrorResponseSchema },
    summary: 'Get prefix list by ID',
    description: 'Returns a single prefix list by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createPrefixList: {
    method: 'POST',
    path: '/bgp/prefix-lists',
    body: CreatePrefixListRequestSchema,
    responses: { ...authedErrorResponses, 201: PrefixListSchema, 400: ErrorResponseSchema },
    summary: 'Create prefix list',
    description: 'Creates a new prefix list.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updatePrefixList: {
    method: 'PATCH',
    path: '/bgp/prefix-lists/:id',
    pathParams: IdParamSchema,
    body: UpdatePrefixListRequestSchema,
    responses: { ...authedErrorResponses, 200: PrefixListSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
    summary: 'Update prefix list',
    description: 'Updates an existing prefix list by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deletePrefixList: {
    method: 'DELETE',
    path: '/bgp/prefix-lists/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: {
      ...authedErrorResponses,
      204: z.void(),
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Delete prefix list',
    description:
      'Deletes a prefix list by its UUID. Fails with 409 if any BGP sessions still reference the list (inbound or outbound).',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listPrefixListRules: {
    method: 'GET',
    path: '/bgp/prefix-list-rules',
    query: PrefixListRuleListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(PrefixListRuleSchema) },
    summary: 'List prefix list rules',
    description: 'Returns a list of prefix list rules, optionally filtered by parent prefix list.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getPrefixListRule: {
    method: 'GET',
    path: '/bgp/prefix-list-rules/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: PrefixListRuleSchema, 404: ErrorResponseSchema },
    summary: 'Get prefix list rule by ID',
    description: 'Returns a single prefix list rule by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createPrefixListRule: {
    method: 'POST',
    path: '/bgp/prefix-list-rules',
    body: CreatePrefixListRuleRequestSchema,
    responses: { ...authedErrorResponses, 201: PrefixListRuleSchema, 400: ErrorResponseSchema },
    summary: 'Create prefix list rule',
    description: 'Creates a new prefix list rule within a prefix list.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updatePrefixListRule: {
    method: 'PATCH',
    path: '/bgp/prefix-list-rules/:id',
    pathParams: IdParamSchema,
    body: UpdatePrefixListRuleRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: PrefixListRuleSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update prefix list rule',
    description: 'Updates an existing prefix list rule by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deletePrefixListRule: {
    method: 'DELETE',
    path: '/bgp/prefix-list-rules/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete prefix list rule',
    description: 'Deletes a prefix list rule by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listBgpSessions: {
    method: 'GET',
    path: '/bgp/sessions',
    query: BgpSessionListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(BgpSessionSchema) },
    summary: 'List BGP sessions',
    description: 'Returns a list of BGP sessions, optionally filtered by organization, device, peer group, or status.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getBgpSession: {
    method: 'GET',
    path: '/bgp/sessions/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: BgpSessionSchema, 404: ErrorResponseSchema },
    summary: 'Get BGP session by ID',
    description: 'Returns a single BGP session by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createBgpSession: {
    method: 'POST',
    path: '/bgp/sessions',
    body: CreateBgpSessionRequestSchema,
    responses: { ...authedErrorResponses, 201: BgpSessionSchema, 400: ErrorResponseSchema },
    summary: 'Create BGP session',
    description: 'Creates a new BGP session.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateBgpSession: {
    method: 'PATCH',
    path: '/bgp/sessions/:id',
    pathParams: IdParamSchema,
    body: UpdateBgpSessionRequestSchema,
    responses: { ...authedErrorResponses, 200: BgpSessionSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
    summary: 'Update BGP session',
    description: 'Updates an existing BGP session by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteBgpSession: {
    method: 'DELETE',
    path: '/bgp/sessions/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete BGP session',
    description: 'Deletes a BGP session by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
});
