import { initContract } from '@ts-rest/core';
import { z } from 'zod';
import {
  CircuitListQuerySchema,
  CircuitSchema,
  CircuitTerminationListQuerySchema,
  CircuitTerminationSchema,
  CircuitTypeListQuerySchema,
  CircuitTypeSchema,
  CreateCircuitRequestSchema,
  CreateCircuitTerminationRequestSchema,
  CreateCircuitTypeRequestSchema,
  CreateProviderNetworkRequestSchema,
  CreateProviderRequestSchema,
  ProviderListQuerySchema,
  ProviderNetworkListQuerySchema,
  ProviderNetworkSchema,
  ProviderSchema,
  UpdateCircuitRequestSchema,
  UpdateCircuitTerminationRequestSchema,
  UpdateCircuitTypeRequestSchema,
  UpdateProviderNetworkRequestSchema,
  UpdateProviderRequestSchema,
} from '../schemas/circuits';
import { ErrorResponseSchema } from '../schemas/responses';
import { type RouteMetadata } from './metadata';
import { authedErrorResponses, authedRoleGatedErrorResponses } from './responses';

const c = initContract();
const IdParamSchema = z.object({ id: z.string().uuid() });

export const circuitsRoutes = c.router({
  listProviders: {
    method: 'GET',
    path: '/circuits/providers',
    query: ProviderListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(ProviderSchema) },
    summary: 'List providers',
    description: 'Returns a list of circuit providers, optionally filtered by search term.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getProvider: {
    method: 'GET',
    path: '/circuits/providers/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: ProviderSchema, 404: ErrorResponseSchema },
    summary: 'Get provider by ID',
    description: 'Returns a single circuit provider by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createProvider: {
    method: 'POST',
    path: '/circuits/providers',
    body: CreateProviderRequestSchema,
    responses: { ...authedRoleGatedErrorResponses, 201: ProviderSchema, 400: ErrorResponseSchema },
    summary: 'Create provider',
    description: 'Creates a new circuit provider.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateProvider: {
    method: 'PATCH',
    path: '/circuits/providers/:id',
    pathParams: IdParamSchema,
    body: UpdateProviderRequestSchema,
    responses: {
      ...authedRoleGatedErrorResponses,
      200: ProviderSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update provider',
    description: 'Updates an existing circuit provider by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteProvider: {
    method: 'DELETE',
    path: '/circuits/providers/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedRoleGatedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete provider',
    description: 'Deletes a circuit provider by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listProviderNetworks: {
    method: 'GET',
    path: '/circuits/provider-networks',
    query: ProviderNetworkListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(ProviderNetworkSchema) },
    summary: 'List provider networks',
    description: 'Returns a list of provider networks, optionally filtered by provider or search term.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getProviderNetwork: {
    method: 'GET',
    path: '/circuits/provider-networks/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: ProviderNetworkSchema, 404: ErrorResponseSchema },
    summary: 'Get provider network by ID',
    description: 'Returns a single provider network by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createProviderNetwork: {
    method: 'POST',
    path: '/circuits/provider-networks',
    body: CreateProviderNetworkRequestSchema,
    responses: { ...authedRoleGatedErrorResponses, 201: ProviderNetworkSchema, 400: ErrorResponseSchema },
    summary: 'Create provider network',
    description: 'Creates a new provider network.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateProviderNetwork: {
    method: 'PATCH',
    path: '/circuits/provider-networks/:id',
    pathParams: IdParamSchema,
    body: UpdateProviderNetworkRequestSchema,
    responses: {
      ...authedRoleGatedErrorResponses,
      200: ProviderNetworkSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update provider network',
    description: 'Updates an existing provider network by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteProviderNetwork: {
    method: 'DELETE',
    path: '/circuits/provider-networks/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedRoleGatedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete provider network',
    description: 'Deletes a provider network by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listCircuitTypes: {
    method: 'GET',
    path: '/circuits/circuit-types',
    query: CircuitTypeListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(CircuitTypeSchema) },
    summary: 'List circuit types',
    description: 'Returns a list of circuit types, optionally filtered by search term.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getCircuitType: {
    method: 'GET',
    path: '/circuits/circuit-types/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: CircuitTypeSchema, 404: ErrorResponseSchema },
    summary: 'Get circuit type by ID',
    description: 'Returns a single circuit type by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createCircuitType: {
    method: 'POST',
    path: '/circuits/circuit-types',
    body: CreateCircuitTypeRequestSchema,
    responses: { ...authedRoleGatedErrorResponses, 201: CircuitTypeSchema, 400: ErrorResponseSchema },
    summary: 'Create circuit type',
    description: 'Creates a new circuit type definition.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateCircuitType: {
    method: 'PATCH',
    path: '/circuits/circuit-types/:id',
    pathParams: IdParamSchema,
    body: UpdateCircuitTypeRequestSchema,
    responses: {
      ...authedRoleGatedErrorResponses,
      200: CircuitTypeSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update circuit type',
    description: 'Updates an existing circuit type by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteCircuitType: {
    method: 'DELETE',
    path: '/circuits/circuit-types/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: {
      ...authedRoleGatedErrorResponses,
      204: z.void(),
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Delete circuit type',
    description: 'Deletes a circuit type by its UUID. Fails with 409 if any circuits still reference the type.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listCircuits: {
    method: 'GET',
    path: '/circuits/circuits',
    query: CircuitListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(CircuitSchema) },
    summary: 'List circuits',
    description: 'Returns a list of circuits, optionally filtered by provider, type, or status.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getCircuit: {
    method: 'GET',
    path: '/circuits/circuits/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: CircuitSchema, 404: ErrorResponseSchema },
    summary: 'Get circuit by ID',
    description: 'Returns a single circuit by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createCircuit: {
    method: 'POST',
    path: '/circuits/circuits',
    body: CreateCircuitRequestSchema,
    responses: { ...authedErrorResponses, 201: CircuitSchema, 400: ErrorResponseSchema },
    summary: 'Create circuit',
    description: 'Creates a new circuit record.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateCircuit: {
    method: 'PATCH',
    path: '/circuits/circuits/:id',
    pathParams: IdParamSchema,
    body: UpdateCircuitRequestSchema,
    responses: { ...authedErrorResponses, 200: CircuitSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
    summary: 'Update circuit',
    description: 'Updates an existing circuit by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteCircuit: {
    method: 'DELETE',
    path: '/circuits/circuits/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete circuit',
    description: 'Deletes a circuit by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listCircuitTerminations: {
    method: 'GET',
    path: '/circuits/circuit-terminations',
    query: CircuitTerminationListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(CircuitTerminationSchema) },
    summary: 'List circuit terminations',
    description: 'Returns a list of circuit terminations, optionally filtered by circuit or zone.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getCircuitTermination: {
    method: 'GET',
    path: '/circuits/circuit-terminations/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: CircuitTerminationSchema, 404: ErrorResponseSchema },
    summary: 'Get circuit termination by ID',
    description: 'Returns a single circuit termination by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createCircuitTermination: {
    method: 'POST',
    path: '/circuits/circuit-terminations',
    body: CreateCircuitTerminationRequestSchema,
    responses: { ...authedErrorResponses, 201: CircuitTerminationSchema, 400: ErrorResponseSchema },
    summary: 'Create circuit termination',
    description: 'Creates a new circuit termination.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateCircuitTermination: {
    method: 'PATCH',
    path: '/circuits/circuit-terminations/:id',
    pathParams: IdParamSchema,
    body: UpdateCircuitTerminationRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: CircuitTerminationSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update circuit termination',
    description: 'Updates an existing circuit termination by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteCircuitTermination: {
    method: 'DELETE',
    path: '/circuits/circuit-terminations/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete circuit termination',
    description: 'Deletes a circuit termination by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
});
