import { initContract } from '@ts-rest/core';
import { z } from 'zod';
import {
  ConnectionsQuerySchema,
  ConsoleConnectionSchema,
  InterfaceConnectionSchema,
  PowerConnectionSchema,
} from '../schemas/connections';
import {
  BulkUpdateDeviceInterfacesRequestSchema,
  CreateDcimCableRequestSchema,
  CreateDcimConsolePortRequestSchema,
  CreateDcimConsoleServerPortRequestSchema,
  CreateDcimFrontPortRequestSchema,
  CreateDcimInterfaceRequestSchema,
  CreateDcimPowerOutletRequestSchema,
  CreateDcimPowerPortRequestSchema,
  CreateDcimRackRequestSchema,
  CreateDcimRearPortRequestSchema,
  DcimCableListQuerySchema,
  DcimCableListResponseSchema,
  DcimCableSchema,
  DcimConsolePortListQuerySchema,
  DcimConsolePortListResponseSchema,
  DcimConsolePortSchema,
  DcimConsoleServerPortListQuerySchema,
  DcimConsoleServerPortListResponseSchema,
  DcimConsoleServerPortSchema,
  DcimFrontPortListQuerySchema,
  DcimFrontPortListResponseSchema,
  DcimFrontPortSchema,
  DcimInterfaceListQuerySchema,
  DcimInterfaceListResponseSchema,
  DcimInterfaceSchema,
  DcimPowerOutletListQuerySchema,
  DcimPowerOutletListResponseSchema,
  DcimPowerOutletSchema,
  DcimPowerPortListQuerySchema,
  DcimPowerPortListResponseSchema,
  DcimPowerPortSchema,
  DcimRackListQuerySchema,
  DcimRackListResponseSchema,
  DcimRackSchema,
  DcimRearPortListQuerySchema,
  DcimRearPortListResponseSchema,
  DcimRearPortSchema,
  DeviceInterfacesResponseSchema,
  UpdateDcimCableRequestSchema,
  UpdateDcimConsolePortRequestSchema,
  UpdateDcimConsoleServerPortRequestSchema,
  UpdateDcimFrontPortRequestSchema,
  UpdateDcimInterfaceRequestSchema,
  UpdateDcimPowerOutletRequestSchema,
  UpdateDcimPowerPortRequestSchema,
  UpdateDcimRackRequestSchema,
  UpdateDcimRearPortRequestSchema,
} from '../schemas/dcim';
import { RackElevationQuerySchema, RackElevationUnitSchema } from '../schemas/elevations';
import { ErrorResponseSchema } from '../schemas/responses';
import { type RouteMetadata } from './metadata';
import { authedErrorResponses } from './responses';

const c = initContract();

const IdParamSchema = z.object({
  id: z.string().uuid(),
});

export const dcimRoutes = c.router({
  listDcimInterfaces: {
    method: 'GET',
    path: '/dcim/interfaces',
    query: DcimInterfaceListQuerySchema,
    responses: { ...authedErrorResponses, 200: DcimInterfaceListResponseSchema },
    summary: 'List interfaces',
    description:
      'Returns a paginated list of network interfaces. Supports server-side `page`/`pageSize`/`sort`/`search`, plus discrete filters `deviceId`, `type`, `enabled`, and `linkType`.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getDcimInterface: {
    method: 'GET',
    path: '/dcim/interfaces/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: DcimInterfaceSchema, 404: ErrorResponseSchema },
    summary: 'Get interface by ID',
    description: 'Returns a single network interface by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createDcimInterface: {
    method: 'POST',
    path: '/dcim/interfaces',
    body: CreateDcimInterfaceRequestSchema,
    responses: { ...authedErrorResponses, 201: DcimInterfaceSchema, 400: ErrorResponseSchema },
    summary: 'Create interface',
    description: 'Creates a new network interface on a device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateDcimInterface: {
    method: 'PATCH',
    path: '/dcim/interfaces/:id',
    pathParams: IdParamSchema,
    body: UpdateDcimInterfaceRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: DcimInterfaceSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update interface',
    description: 'Updates an existing network interface by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteDcimInterface: {
    method: 'DELETE',
    path: '/dcim/interfaces/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete interface',
    description: 'Deletes a network interface by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  listDeviceInterfaces: {
    method: 'GET',
    path: '/dcim/devices/:deviceId/interfaces',
    pathParams: z.object({ deviceId: z.string().uuid() }),
    responses: { ...authedErrorResponses, 200: DeviceInterfacesResponseSchema, 404: ErrorResponseSchema },
    summary: 'List a device’s interfaces',
    description:
      'Returns every network interface on a device, each with its assigned IP addresses. Powers the server and bridge Interfaces tab.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  bulkUpdateDeviceInterfaces: {
    method: 'POST',
    path: '/dcim/devices/:deviceId/interfaces/bulk',
    pathParams: z.object({ deviceId: z.string().uuid() }),
    body: BulkUpdateDeviceInterfacesRequestSchema,
    responses: { ...authedErrorResponses, 204: z.void(), 400: ErrorResponseSchema, 404: ErrorResponseSchema },
    summary: 'Bulk-apply interface changes',
    description:
      'Applies creates, updates, and deletes to a device’s interfaces in a single transaction, so renames and name swaps are atomic and roll back together on any failure.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listDcimRacks: {
    method: 'GET',
    path: '/dcim/racks',
    query: DcimRackListQuerySchema,
    responses: { ...authedErrorResponses, 200: DcimRackListResponseSchema },
    summary: 'List racks',
    description: 'Returns a list of racks, optionally filtered by zone, status, or role.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getDcimRack: {
    method: 'GET',
    path: '/dcim/racks/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: DcimRackSchema, 404: ErrorResponseSchema },
    summary: 'Get rack by ID',
    description: 'Returns a single rack by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createDcimRack: {
    method: 'POST',
    path: '/dcim/racks',
    body: CreateDcimRackRequestSchema,
    responses: { ...authedErrorResponses, 201: DcimRackSchema, 400: ErrorResponseSchema },
    summary: 'Create rack',
    description: 'Creates a new rack in a zone.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateDcimRack: {
    method: 'PATCH',
    path: '/dcim/racks/:id',
    pathParams: IdParamSchema,
    body: UpdateDcimRackRequestSchema,
    responses: { ...authedErrorResponses, 200: DcimRackSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
    summary: 'Update rack',
    description: 'Updates an existing rack by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteDcimRack: {
    method: 'DELETE',
    path: '/dcim/racks/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete rack',
    description: 'Deletes a rack by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listDcimCables: {
    method: 'GET',
    path: '/dcim/cables',
    query: DcimCableListQuerySchema,
    responses: { ...authedErrorResponses, 200: DcimCableListResponseSchema },
    summary: 'List cables',
    description: 'Returns a list of cables, optionally filtered by status or type.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getDcimCable: {
    method: 'GET',
    path: '/dcim/cables/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: DcimCableSchema, 404: ErrorResponseSchema },
    summary: 'Get cable by ID',
    description: 'Returns a single cable by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createDcimCable: {
    method: 'POST',
    path: '/dcim/cables',
    body: CreateDcimCableRequestSchema,
    responses: { ...authedErrorResponses, 201: DcimCableSchema, 400: ErrorResponseSchema },
    summary: 'Create cable',
    description:
      'Creates a cable connecting two ports. Both an A-side and a B-side termination are required, and their port types must be compatible.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateDcimCable: {
    method: 'PATCH',
    path: '/dcim/cables/:id',
    pathParams: IdParamSchema,
    body: UpdateDcimCableRequestSchema,
    responses: { ...authedErrorResponses, 200: DcimCableSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
    summary: 'Update cable',
    description: 'Updates an existing cable by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteDcimCable: {
    method: 'DELETE',
    path: '/dcim/cables/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete cable',
    description: 'Deletes a cable by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listDcimConsolePorts: {
    method: 'GET',
    path: '/dcim/console-ports',
    query: DcimConsolePortListQuerySchema,
    responses: { ...authedErrorResponses, 200: DcimConsolePortListResponseSchema },
    summary: 'List console ports',
    description: 'Returns a list of console ports, optionally filtered by device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getDcimConsolePort: {
    method: 'GET',
    path: '/dcim/console-ports/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: DcimConsolePortSchema, 404: ErrorResponseSchema },
    summary: 'Get console port by ID',
    description: 'Returns a single console port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createDcimConsolePort: {
    method: 'POST',
    path: '/dcim/console-ports',
    body: CreateDcimConsolePortRequestSchema,
    responses: { ...authedErrorResponses, 201: DcimConsolePortSchema, 400: ErrorResponseSchema },
    summary: 'Create console port',
    description: 'Creates a new console port on a device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateDcimConsolePort: {
    method: 'PATCH',
    path: '/dcim/console-ports/:id',
    pathParams: IdParamSchema,
    body: UpdateDcimConsolePortRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: DcimConsolePortSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update console port',
    description: 'Updates an existing console port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteDcimConsolePort: {
    method: 'DELETE',
    path: '/dcim/console-ports/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete console port',
    description: 'Deletes a console port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listDcimConsoleServerPorts: {
    method: 'GET',
    path: '/dcim/console-server-ports',
    query: DcimConsoleServerPortListQuerySchema,
    responses: { ...authedErrorResponses, 200: DcimConsoleServerPortListResponseSchema },
    summary: 'List console server ports',
    description: 'Returns a list of console server ports, optionally filtered by device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getDcimConsoleServerPort: {
    method: 'GET',
    path: '/dcim/console-server-ports/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: DcimConsoleServerPortSchema, 404: ErrorResponseSchema },
    summary: 'Get console server port by ID',
    description: 'Returns a single console server port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createDcimConsoleServerPort: {
    method: 'POST',
    path: '/dcim/console-server-ports',
    body: CreateDcimConsoleServerPortRequestSchema,
    responses: { ...authedErrorResponses, 201: DcimConsoleServerPortSchema, 400: ErrorResponseSchema },
    summary: 'Create console server port',
    description: 'Creates a new console server port on a device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateDcimConsoleServerPort: {
    method: 'PATCH',
    path: '/dcim/console-server-ports/:id',
    pathParams: IdParamSchema,
    body: UpdateDcimConsoleServerPortRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: DcimConsoleServerPortSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update console server port',
    description: 'Updates an existing console server port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteDcimConsoleServerPort: {
    method: 'DELETE',
    path: '/dcim/console-server-ports/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete console server port',
    description: 'Deletes a console server port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listDcimPowerPorts: {
    method: 'GET',
    path: '/dcim/power-ports',
    query: DcimPowerPortListQuerySchema,
    responses: { ...authedErrorResponses, 200: DcimPowerPortListResponseSchema },
    summary: 'List power ports',
    description: 'Returns a list of power ports, optionally filtered by device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getDcimPowerPort: {
    method: 'GET',
    path: '/dcim/power-ports/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: DcimPowerPortSchema, 404: ErrorResponseSchema },
    summary: 'Get power port by ID',
    description: 'Returns a single power port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createDcimPowerPort: {
    method: 'POST',
    path: '/dcim/power-ports',
    body: CreateDcimPowerPortRequestSchema,
    responses: { ...authedErrorResponses, 201: DcimPowerPortSchema, 400: ErrorResponseSchema },
    summary: 'Create power port',
    description: 'Creates a new power port on a device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateDcimPowerPort: {
    method: 'PATCH',
    path: '/dcim/power-ports/:id',
    pathParams: IdParamSchema,
    body: UpdateDcimPowerPortRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: DcimPowerPortSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update power port',
    description: 'Updates an existing power port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteDcimPowerPort: {
    method: 'DELETE',
    path: '/dcim/power-ports/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete power port',
    description: 'Deletes a power port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listDcimPowerOutlets: {
    method: 'GET',
    path: '/dcim/power-outlets',
    query: DcimPowerOutletListQuerySchema,
    responses: { ...authedErrorResponses, 200: DcimPowerOutletListResponseSchema },
    summary: 'List power outlets',
    description: 'Returns a list of power outlets, optionally filtered by device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getDcimPowerOutlet: {
    method: 'GET',
    path: '/dcim/power-outlets/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: DcimPowerOutletSchema, 404: ErrorResponseSchema },
    summary: 'Get power outlet by ID',
    description: 'Returns a single power outlet by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createDcimPowerOutlet: {
    method: 'POST',
    path: '/dcim/power-outlets',
    body: CreateDcimPowerOutletRequestSchema,
    responses: { ...authedErrorResponses, 201: DcimPowerOutletSchema, 400: ErrorResponseSchema },
    summary: 'Create power outlet',
    description: 'Creates a new power outlet on a device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateDcimPowerOutlet: {
    method: 'PATCH',
    path: '/dcim/power-outlets/:id',
    pathParams: IdParamSchema,
    body: UpdateDcimPowerOutletRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: DcimPowerOutletSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update power outlet',
    description: 'Updates an existing power outlet by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteDcimPowerOutlet: {
    method: 'DELETE',
    path: '/dcim/power-outlets/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete power outlet',
    description: 'Deletes a power outlet by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listDcimFrontPorts: {
    method: 'GET',
    path: '/dcim/front-ports',
    query: DcimFrontPortListQuerySchema,
    responses: { ...authedErrorResponses, 200: DcimFrontPortListResponseSchema },
    summary: 'List front ports',
    description: 'Returns a list of front ports, optionally filtered by device or rear port.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getDcimFrontPort: {
    method: 'GET',
    path: '/dcim/front-ports/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: DcimFrontPortSchema, 404: ErrorResponseSchema },
    summary: 'Get front port by ID',
    description: 'Returns a single front port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createDcimFrontPort: {
    method: 'POST',
    path: '/dcim/front-ports',
    body: CreateDcimFrontPortRequestSchema,
    responses: { ...authedErrorResponses, 201: DcimFrontPortSchema, 400: ErrorResponseSchema },
    summary: 'Create front port',
    description: 'Creates a new front port on a device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateDcimFrontPort: {
    method: 'PATCH',
    path: '/dcim/front-ports/:id',
    pathParams: IdParamSchema,
    body: UpdateDcimFrontPortRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: DcimFrontPortSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update front port',
    description: 'Updates an existing front port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteDcimFrontPort: {
    method: 'DELETE',
    path: '/dcim/front-ports/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete front port',
    description: 'Deletes a front port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listDcimRearPorts: {
    method: 'GET',
    path: '/dcim/rear-ports',
    query: DcimRearPortListQuerySchema,
    responses: { ...authedErrorResponses, 200: DcimRearPortListResponseSchema },
    summary: 'List rear ports',
    description: 'Returns a list of rear ports, optionally filtered by device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  getDcimRearPort: {
    method: 'GET',
    path: '/dcim/rear-ports/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: DcimRearPortSchema, 404: ErrorResponseSchema },
    summary: 'Get rear port by ID',
    description: 'Returns a single rear port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  createDcimRearPort: {
    method: 'POST',
    path: '/dcim/rear-ports',
    body: CreateDcimRearPortRequestSchema,
    responses: { ...authedErrorResponses, 201: DcimRearPortSchema, 400: ErrorResponseSchema },
    summary: 'Create rear port',
    description: 'Creates a new rear port on a device.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  updateDcimRearPort: {
    method: 'PATCH',
    path: '/dcim/rear-ports/:id',
    pathParams: IdParamSchema,
    body: UpdateDcimRearPortRequestSchema,
    responses: { ...authedErrorResponses, 200: DcimRearPortSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
    summary: 'Update rear port',
    description: 'Updates an existing rear port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  deleteDcimRearPort: {
    method: 'DELETE',
    path: '/dcim/rear-ports/:id',
    pathParams: IdParamSchema,
    body: z.object({}),
    responses: { ...authedErrorResponses, 204: z.void(), 404: ErrorResponseSchema },
    summary: 'Delete rear port',
    description: 'Deletes a rear port by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  getDcimRackElevation: {
    method: 'GET',
    path: '/dcim/racks/:id/elevation',
    pathParams: IdParamSchema,
    query: RackElevationQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(RackElevationUnitSchema), 404: ErrorResponseSchema },
    summary: 'Get rack elevation',
    description: 'Returns the rack elevation view showing unit occupancy for a given rack.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },

  listDcimInterfaceConnections: {
    method: 'GET',
    path: '/dcim/interface-connections',
    query: ConnectionsQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(InterfaceConnectionSchema) },
    summary: 'List interface connections',
    description: 'Returns a list of interface-to-interface connections, optionally filtered by device or zone.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  listDcimConsoleConnections: {
    method: 'GET',
    path: '/dcim/console-connections',
    query: ConnectionsQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(ConsoleConnectionSchema) },
    summary: 'List console connections',
    description:
      'Returns a list of console port to console server port connections, optionally filtered by device or zone.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  listDcimPowerConnections: {
    method: 'GET',
    path: '/dcim/power-connections',
    query: ConnectionsQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(PowerConnectionSchema) },
    summary: 'List power connections',
    description: 'Returns a list of power port to power outlet connections, optionally filtered by device or zone.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
});
