import { initContract } from '@ts-rest/core';
import { z } from 'zod';
import {
  AllocateNextPrefixRequestSchema,
  CreateIpAddressRequestSchema,
  CreateIpRangeRequestSchema,
  CreatePrefixRequestSchema,
  CreateVlanRequestSchema,
  CreateVrfRequestSchema,
  DetectIpRangeOverlapRequestSchema,
  DetectPrefixOverlapRequestSchema,
  DhcpLeaseSchema,
  DhcpReservationSchema,
  IpAddressListQuerySchema,
  IpAddressSchema,
  IpamChangelogEntrySchema,
  IpamChangelogQuerySchema,
  IpRangeListQuerySchema,
  IpRangeOverlapResultSchema,
  IpRangeSchema,
  PrefixDhcpConfigSchema,
  PrefixDhcpServingSchema,
  PrefixListQuerySchema,
  PrefixOverlapResultSchema,
  PrefixSchema,
  PrefixUtilizationSchema,
  UpdateIpAddressRequestSchema,
  UpdateIpRangeRequestSchema,
  UpdatePrefixDhcpConfigSchema,
  UpdatePrefixRequestSchema,
  UpdateVlanRequestSchema,
  UpdateVrfRequestSchema,
  ValidatePrefixGatewayRequestSchema,
  ValidatePrefixGatewayResultSchema,
  VlanListQuerySchema,
  VlanSchema,
  VrfListQuerySchema,
  VrfSchema,
  VrrpBindingSchema,
  VrrpBindingsSchema,
} from '../schemas/ipam';
import { ErrorResponseSchema } from '../schemas/responses';
import { type RouteMetadata } from './metadata';
import { authedErrorResponses } from './responses';

const c = initContract();

const IdParamSchema = z.object({
  id: z.string().uuid(),
});

export const ipamRoutes = c.router({
  getVrf: {
    method: 'GET',
    path: '/ipam/vrfs/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: VrfSchema, 404: ErrorResponseSchema },
    summary: 'Get VRF by ID',
    description: 'Returns a single VRF by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  listVrfs: {
    method: 'GET',
    path: '/ipam/vrfs',
    query: VrfListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(VrfSchema) },
    summary: 'List VRFs',
    description:
      "Returns the organization's VRFs (virtual routing & forwarding instances), optionally filtered by search.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  createVrf: {
    method: 'POST',
    path: '/ipam/vrfs',
    body: CreateVrfRequestSchema,
    responses: { ...authedErrorResponses, 201: VrfSchema, 400: ErrorResponseSchema, 409: ErrorResponseSchema },
    summary: 'Create VRF',
    description: 'Creates a new VRF (virtual routing & forwarding instance) for routing-table isolation.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  updateVrf: {
    method: 'PATCH',
    path: '/ipam/vrfs/:id',
    pathParams: IdParamSchema,
    body: UpdateVrfRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: VrfSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Update VRF',
    description: "Updates an existing VRF's name, route distinguisher, or description.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  archiveVrf: {
    method: 'DELETE',
    path: '/ipam/vrfs/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: VrfSchema, 404: ErrorResponseSchema },
    summary: 'Archive VRF',
    description: 'Soft-deletes (archives) a VRF by its UUID.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  getPrefix: {
    method: 'GET',
    path: '/ipam/prefixes/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: PrefixSchema, 404: ErrorResponseSchema },
    summary: 'Get prefix by ID',
    description: 'Returns a single prefix by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  listPrefixes: {
    method: 'GET',
    path: '/ipam/prefixes',
    query: PrefixListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(PrefixSchema) },
    summary: 'List prefixes',
    description:
      "Returns the organization's prefixes (CIDR network blocks), optionally filtered by VRF, status, parent, or VLAN.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  createPrefix: {
    method: 'POST',
    path: '/ipam/prefixes',
    body: CreatePrefixRequestSchema,
    responses: {
      ...authedErrorResponses,
      201: PrefixSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Create prefix',
    description:
      'Creates a new prefix (CIDR network block), optionally nested under a parent prefix or assigned to a VRF.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  updatePrefix: {
    method: 'PATCH',
    path: '/ipam/prefixes/:id',
    pathParams: IdParamSchema,
    body: UpdatePrefixRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: PrefixSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Update prefix',
    description: "Updates a prefix's status, pool flag, VRF, parent, VLAN, or gateway IP assignment.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  archivePrefix: {
    method: 'DELETE',
    path: '/ipam/prefixes/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: PrefixSchema, 404: ErrorResponseSchema },
    summary: 'Archive prefix',
    description: 'Soft-deletes (archives) a prefix by its UUID.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  setPrefixGateway: {
    method: 'POST',
    path: '/ipam/prefixes/:id/gateway',
    pathParams: IdParamSchema,
    body: z.object({ gatewayIpId: z.string().uuid() }),
    responses: { ...authedErrorResponses, 200: PrefixSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
    summary: 'Set gateway IP for prefix',
    description: 'Assigns an existing IP address as the default gateway for the prefix.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  clearPrefixGateway: {
    method: 'DELETE',
    path: '/ipam/prefixes/:id/gateway',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: PrefixSchema, 404: ErrorResponseSchema },
    summary: 'Clear gateway IP for prefix',
    description: 'Removes the gateway IP assignment from the prefix.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  setPrefixVrrpVip: {
    method: 'POST',
    path: '/ipam/prefixes/:id/vrrp-vip',
    pathParams: IdParamSchema,
    body: z.object({
      vrrpVipId: z
        .string()
        .uuid()
        .describe('Identifier of an existing IP address (within this prefix) to advertise as the VRRP floating IP.'),
      bindings: VrrpBindingsSchema.describe(
        'Per-bridge NIC bindings: each zone bridge that should hold the VIP, with its own NIC name (each bridge ' +
          'at most once). Bridges in the zone that are omitted will not bind the VIP. Replaces any existing ' +
          'bindings for this prefix.',
      ),
    }),
    responses: {
      ...authedErrorResponses,
      200: PrefixSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Set VRRP virtual IP for prefix',
    description:
      "Assigns an existing IP address as the prefix's VRRP floating IP and publishes it, per bridge, to the zone's " +
      'bridges (each on its own NIC). The prefix must be assigned to a zone and have role PRIMARY (the bridge/spoke ' +
      'data-plane subnet); assigning a VIP to any other role returns 400.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  getPrefixVrrpBindings: {
    method: 'GET',
    path: '/ipam/prefixes/:id/vrrp-bindings',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: z.array(VrrpBindingSchema), 404: ErrorResponseSchema },
    summary: 'List per-bridge VRRP bindings for a prefix',
    description:
      "Returns the prefix's current per-bridge VIP NIC bindings (bridge id + iface), prefilling the edit form.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  clearPrefixVrrpVip: {
    method: 'DELETE',
    path: '/ipam/prefixes/:id/vrrp-vip',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: PrefixSchema, 404: ErrorResponseSchema },
    summary: 'Clear VRRP virtual IP for prefix',
    description: "Removes the prefix's VRRP floating IP assignment and withdraws it from the zone's bridges.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  validatePrefixGateway: {
    method: 'POST',
    path: '/ipam/prefixes/validate-gateway',
    body: ValidatePrefixGatewayRequestSchema,
    responses: { ...authedErrorResponses, 200: ValidatePrefixGatewayResultSchema, 404: ErrorResponseSchema },
    summary: 'Validate whether gateway IP can be applied to a prefix',
    description:
      "Checks whether the given IP address is eligible to serve as the prefix's gateway, without applying it.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  listChildPrefixes: {
    method: 'GET',
    path: '/ipam/prefixes/:id/children',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: z.array(PrefixSchema), 404: ErrorResponseSchema },
    summary: 'List child prefixes for a prefix',
    description: 'Returns the immediate child prefixes nested under the given parent prefix.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  listIpsInPrefix: {
    method: 'GET',
    path: '/ipam/prefixes/:id/ip-addresses',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: z.array(IpAddressSchema), 404: ErrorResponseSchema },
    summary: 'List IP addresses within a prefix',
    description: "Returns the IP addresses that fall within the given prefix's CIDR range.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  getPrefixUtilization: {
    method: 'GET',
    path: '/ipam/prefixes/:id/utilization',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: PrefixUtilizationSchema, 404: ErrorResponseSchema },
    summary: 'Get prefix utilization details',
    description:
      'Returns address-space utilization for the prefix (assigned, available, and capacity counts plus percent used).',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  allocateNextPrefix: {
    method: 'POST',
    path: '/ipam/prefixes/:id/allocate-prefix',
    pathParams: IdParamSchema,
    body: AllocateNextPrefixRequestSchema,
    responses: {
      ...authedErrorResponses,
      201: PrefixSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Allocate next available child prefix',
    description: 'Carves out the next free child prefix of the requested mask length from within the parent prefix.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  detectPrefixOverlap: {
    method: 'POST',
    path: '/ipam/prefixes/overlap-check',
    body: DetectPrefixOverlapRequestSchema,
    responses: { ...authedErrorResponses, 200: PrefixOverlapResultSchema, 400: ErrorResponseSchema },
    summary: 'Check whether a candidate prefix overlaps',
    description: 'Checks whether a candidate CIDR block overlaps any existing prefix in the same VRF.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  getVlan: {
    method: 'GET',
    path: '/ipam/vlans/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: VlanSchema, 404: ErrorResponseSchema },
    summary: 'Get VLAN by ID',
    description: 'Returns a single VLAN by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  listVlans: {
    method: 'GET',
    path: '/ipam/vlans',
    query: VlanListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(VlanSchema) },
    summary: 'List VLANs',
    description: "Returns the organization's VLANs (layer-2 segments), optionally filtered by VRF or status.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  createVlan: {
    method: 'POST',
    path: '/ipam/vlans',
    body: CreateVlanRequestSchema,
    responses: {
      ...authedErrorResponses,
      201: VlanSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Create VLAN',
    description: 'Creates a new VLAN (layer-2 segment) with an 802.1Q VLAN ID.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  updateVlan: {
    method: 'PATCH',
    path: '/ipam/vlans/:id',
    pathParams: IdParamSchema,
    body: UpdateVlanRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: VlanSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Update VLAN',
    description: "Updates a VLAN's name, VLAN ID, description, status, or VRF assignment.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  archiveVlan: {
    method: 'DELETE',
    path: '/ipam/vlans/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: VlanSchema, 404: ErrorResponseSchema },
    summary: 'Archive VLAN',
    description: 'Soft-deletes (archives) a VLAN by its UUID.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  getIpRange: {
    method: 'GET',
    path: '/ipam/ip-ranges/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: IpRangeSchema, 404: ErrorResponseSchema },
    summary: 'Get IP range by ID',
    description: 'Returns a single IP range by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  listIpRanges: {
    method: 'GET',
    path: '/ipam/ip-ranges',
    query: IpRangeListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(IpRangeSchema) },
    summary: 'List IP ranges',
    description:
      "Returns the organization's IP ranges (contiguous address spans), optionally filtered by prefix, VRF, or status.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  createIpRange: {
    method: 'POST',
    path: '/ipam/ip-ranges',
    body: CreateIpRangeRequestSchema,
    responses: {
      ...authedErrorResponses,
      201: IpRangeSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Create IP range',
    description: 'Creates a contiguous span of IP addresses (start–end) within a parent prefix.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  updateIpRange: {
    method: 'PATCH',
    path: '/ipam/ip-ranges/:id',
    pathParams: IdParamSchema,
    body: UpdateIpRangeRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: IpRangeSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Update IP range',
    description: "Updates an IP range's start/end bounds, status, purpose, or VRF assignment.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  archiveIpRange: {
    method: 'DELETE',
    path: '/ipam/ip-ranges/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: IpRangeSchema, 404: ErrorResponseSchema },
    summary: 'Archive IP range',
    description: 'Soft-deletes (archives) an IP range by its UUID.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  detectIpRangeOverlap: {
    method: 'POST',
    path: '/ipam/ip-ranges/overlap-check',
    body: DetectIpRangeOverlapRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: IpRangeOverlapResultSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Check whether an IP range overlaps existing ranges',
    description: 'Checks whether a candidate start–end span overlaps any existing IP range in the same prefix and VRF.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  getIpAddress: {
    method: 'GET',
    path: '/ipam/ip-addresses/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: IpAddressSchema, 404: ErrorResponseSchema },
    summary: 'Get IP address by ID',
    description: 'Returns a single IP address by its UUID.',
    metadata: { visibility: 'internal' } satisfies RouteMetadata,
  },
  listIpAddresses: {
    method: 'GET',
    path: '/ipam/ip-addresses',
    query: IpAddressListQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(IpAddressSchema) },
    summary: 'List IP addresses',
    description:
      "Returns the organization's IP addresses, optionally filtered by VRF, status, prefix, or assigned object.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  createIpAddress: {
    method: 'POST',
    path: '/ipam/ip-addresses',
    body: CreateIpAddressRequestSchema,
    responses: {
      ...authedErrorResponses,
      201: IpAddressSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Create IP address',
    description: 'Creates a new IP address record, optionally with a DNS name and VRF assignment.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  updateIpAddress: {
    method: 'PATCH',
    path: '/ipam/ip-addresses/:id',
    pathParams: IdParamSchema,
    body: UpdateIpAddressRequestSchema,
    responses: {
      ...authedErrorResponses,
      200: IpAddressSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
    },
    summary: 'Update IP address',
    description: "Updates an IP address's status, DNS name, or VRF assignment.",
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  archiveIpAddress: {
    method: 'DELETE',
    path: '/ipam/ip-addresses/:id',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: IpAddressSchema, 404: ErrorResponseSchema },
    summary: 'Archive IP address',
    description: 'Soft-deletes (archives) an IP address by its UUID.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  listIpamChangelog: {
    method: 'GET',
    path: '/ipam/changelog',
    query: IpamChangelogQuerySchema,
    responses: { ...authedErrorResponses, 200: z.array(IpamChangelogEntrySchema) },
    summary: 'List IPAM change log entries',
    description: 'Returns the audit change-log of IPAM record mutations, optionally filtered by table and primary key.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },

  getPrefixDhcpConfig: {
    method: 'GET',
    path: '/ipam/prefixes/:id/dhcp/config',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: PrefixDhcpConfigSchema, 404: ErrorResponseSchema },
    summary: 'Get DHCP config for a prefix',
    description:
      'Returns the stored DHCP policy fields for a prefix (mode, lease TTL, boot target, and custom ' +
      'options). Pools, routers, reservations, next-server, and DNS servers are derived from IPAM at ' +
      'render time (the bridge self-derives next-server/DNS) and are not included here.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  updatePrefixDhcpConfig: {
    method: 'PUT',
    path: '/ipam/prefixes/:id/dhcp/config',
    pathParams: IdParamSchema,
    body: UpdatePrefixDhcpConfigSchema,
    responses: {
      ...authedErrorResponses,
      200: PrefixDhcpConfigSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
    summary: 'Update DHCP config for a prefix',
    description:
      'Replaces the stored DHCP policy fields for a prefix. Set dhcpMode to null or OFF to disable DHCP ' +
      'serving. Custom option codes that are reserved or auto-managed by the bridge are rejected with 400.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  getPrefixDhcpLeases: {
    method: 'GET',
    path: '/ipam/prefixes/:id/dhcp/leases',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: z.array(DhcpLeaseSchema), 404: ErrorResponseSchema },
    summary: 'List active DHCP leases for a prefix',
    description:
      "Returns the bridge's currently-held DHCP leases whose address falls within this prefix, read live " +
      'from the shared lease store. Empty when the prefix has no zone or the bridge has issued no leases.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  getPrefixDhcpReservations: {
    method: 'GET',
    path: '/ipam/prefixes/:id/dhcp/reservations',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: z.array(DhcpReservationSchema), 404: ErrorResponseSchema },
    summary: 'List derived DHCP reservations for a prefix',
    description:
      'Returns the read-only DHCP reservations derived from device-interface IPs within this prefix (the ' +
      'same source the bridge renders into its DHCP atom), each carrying deviceId/interfaceId so the UI can ' +
      'link through to device management. Reservations are derived, never edited here.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
  getPrefixDhcpServing: {
    method: 'GET',
    path: '/ipam/prefixes/:id/dhcp/serving',
    pathParams: IdParamSchema,
    responses: { ...authedErrorResponses, 200: PrefixDhcpServingSchema, 404: ErrorResponseSchema },
    summary: 'Resolve derived DHCP serving addresses for a prefix',
    description:
      'Returns the read-only next-server and DNS server addresses the bridge will use when serving DHCP ' +
      'for this prefix, derived from the VRRP VIP (if assigned) or the bridge NIC IPs within the prefix. ' +
      'Computed on demand — never stored or editable here.',
    metadata: { visibility: 'public' } satisfies RouteMetadata,
  },
});
