#!/usr/bin/env bash
# Renders ./env.local.nix from BROKKR_CFG_* / BROKKR_PIN_*, BEFORE devenv evaluates anything —
# it never calls `devenv eval`, because that eval imports the file being written.
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
TARGET="$ROOT/env.local.nix"
TMP="$TARGET.tmp"
ALIASES="$ROOT/devenv/env-pin-aliases.txt"

warn() { printf 'render-env-pins: %s\n' "$*" >&2; }

# `off` must DELETE the file, not skip the render: devenv.nix imports it whenever it exists, so a
# previous render would keep every pin active while the operator believes they are off.
if [ "${BROKKR_ENV_PINS:-}" = off ]; then
  rm -f "$TARGET" "$TMP"
  exit 0
fi

paths=()
values=()
vars=()

index_of() {
  local i=0
  while [ "$i" -lt "${#paths[@]}" ]; do
    if [ "${paths[$i]}" = "$1" ]; then
      printf '%s' "$i"
      return 0
    fi
    i=$((i + 1))
  done
  return 1
}

# canonical BROKKR_CFG_* wins a duplicate because it is collected first; the loser is named so a
# stale shorthand in a shell profile is visible rather than mysteriously inert.
add_pin() {
  local path=$1 value=$2 var=$3 dup
  if dup=$(index_of "$path"); then
    warn "warning: $var and ${vars[$dup]} both pin '$path' — keeping ${vars[$dup]}"
    return 0
  fi
  paths+=("$path")
  values+=("$value")
  vars+=("$var")
}

# a segment may hold single underscores (env keys like AUTH_BYPASS_ENABLED are one segment), so
# only a doubled underscore separates, and an empty segment means the variable name is malformed.
valid_path() {
  case "$1" in
  '' | .* | *. | *..*) return 1 ;;
  esac
  local rest=$1 seg
  while [ -n "$rest" ]; do
    seg=${rest%%.*}
    case "$seg" in
    *[!A-Za-z0-9_-]*) return 1 ;;
    esac
    [ "$rest" = "$seg" ] && break
    rest=${rest#*.}
  done
  return 0
}

alias_path() {
  local line key
  [ -f "$ALIASES" ] || return 1
  while IFS= read -r line || [ -n "$line" ]; do
    line=${line%$'\r'}
    case "$line" in '' | '#'*) continue ;; esac
    key=${line%%=*}
    if [ "$key" = "$1" ]; then
      printf '%s' "${line#*=}"
      return 0
    fi
  done <"$ALIASES"
  return 1
}

# ${!prefix@} rather than `compgen -v`: compgen is absent from a bash built without programmable
# completion, which is what a non-interactive nix bash is.
for name in ${!BROKKR_CFG_@}; do
  path=${name#BROKKR_CFG_}
  path=${path//__/.}
  if ! valid_path "$path"; then
    warn "warning: $name is not a usable pin — expected BROKKR_CFG_<path with dots written as __>"
    continue
  fi
  if [ -n "${!name}" ]; then
    add_pin "$path" "${!name}" "$name"
  fi
done

for name in ${!BROKKR_PIN_@}; do
  if ! path=$(alias_path "$name"); then
    warn "warning: $name is not a declared shorthand — see devenv/env-pin-aliases.txt"
    continue
  fi
  if [ -n "${!name}" ]; then
    add_pin "$path" "${!name}" "$name"
  fi
done

if [ "${#paths[@]}" -eq 0 ]; then
  rm -f "$TARGET" "$TMP"
  exit 0
fi

escaped=
# A nix double-quoted string accepts a literal newline, but it NORMALISES a literal carriage return
# to a newline — so an unescaped CR in a pin value silently comes back as LF.
nix_escape() {
  escaped=$1
  escaped=${escaped//\\/\\\\}
  escaped=${escaped//\"/\\\"}
  escaped=${escaped//\$/\\\$}
  escaped=${escaped//$'\r'/\\r}
  escaped=${escaped//$'\n'/\\n}
  escaped=${escaped//$'\t'/\\t}
}

# Byte-stable and moved only when the content differs: .envrc watches this file, so an identical
# write with a fresh mtime re-triggers direnv, which re-runs this script.
render() {
  local path i sorted
  sorted=$(printf '%s\n' "${paths[@]}" | sort)
  printf '# Generated by devenv/scripts/render-env-pins.sh from the BROKKR_CFG_* / BROKKR_PIN_*\n'
  printf '# environment. Do not edit: unset the variable and re-enter the shell instead.\n'
  printf '{\n  brokkrEnvPins = {\n'
  for path in $sorted; do
    i=$(index_of "$path")
    nix_escape "${values[$i]}"
    printf '    "%s" = "%s";\n' "$path" "$escaped"
  done
  printf '  };\n\n  brokkrEnvPinVars = {\n'
  for path in $sorted; do
    i=$(index_of "$path")
    printf '    "%s" = "%s";\n' "$path" "${vars[$i]}"
  done
  printf '  };\n}\n'
}

trap 'rm -f "$TMP"' EXIT
render >"$TMP"
if [ -f "$TARGET" ] && [ "$(<"$TMP")" = "$(<"$TARGET")" ]; then
  exit 0
fi
mv -f "$TMP" "$TARGET"
