import type { Control, FieldValues, Path } from 'react-hook-form';
import { FormSelect } from './form-select';

const COUNTRY_OPTIONS = [
  { label: 'United States', value: 'US' },
  { label: 'United Arab Emirates', value: 'AE' },
  { label: 'Antigua and Barbuda', value: 'AG' },
  { label: 'Albania', value: 'AL' },
  { label: 'Armenia', value: 'AM' },
  { label: 'Argentina', value: 'AR' },
  { label: 'Austria', value: 'AT' },
  { label: 'Australia', value: 'AU' },
  { label: 'Bosnia and Herzegovina', value: 'BA' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Bahrain', value: 'BH' },
  { label: 'Benin', value: 'BJ' },
  { label: 'Brunei Darussalam', value: 'BN' },
  { label: 'Bolivia', value: 'BO' },
  { label: 'Brazil', value: 'BR' },
  { label: 'Bahamas', value: 'BS' },
  { label: 'Botswana', value: 'BW' },
  { label: 'Canada', value: 'CA' },
  { label: 'Switzerland', value: 'CH' },
  { label: "Côte D'Ivoire", value: 'CI' },
  { label: 'Chile', value: 'CL' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Costa Rica', value: 'CR' },
  { label: 'Cyprus', value: 'CY' },
  { label: 'Czech Republic', value: 'CZ' },
  { label: 'Germany', value: 'DE' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Dominican Republic', value: 'DO' },
  { label: 'Ecuador', value: 'EC' },
  { label: 'Estonia', value: 'EE' },
  { label: 'Egypt', value: 'EG' },
  { label: 'Spain', value: 'ES' },
  { label: 'Ethiopia', value: 'ET' },
  { label: 'Finland', value: 'FI' },
  { label: 'France', value: 'FR' },
  { label: 'United Kingdom', value: 'GB' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Gambia', value: 'GM' },
  { label: 'Greece', value: 'GR' },
  { label: 'Guatemala', value: 'GT' },
  { label: 'Guyana', value: 'GY' },
  { label: 'Hong Kong', value: 'HK' },
  { label: 'Croatia', value: 'HR' },
  { label: 'Hungary', value: 'HU' },
  { label: 'Indonesia', value: 'ID' },
  { label: 'Ireland', value: 'IE' },
  { label: 'Israel', value: 'IL' },
  { label: 'India', value: 'IN' },
  { label: 'Iceland', value: 'IS' },
  { label: 'Italy', value: 'IT' },
  { label: 'Jamaica', value: 'JM' },
  { label: 'Jordan', value: 'JO' },
  { label: 'Japan', value: 'JP' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Cambodia', value: 'KH' },
  { label: 'Republic of Korea', value: 'KR' },
  { label: 'Kuwait', value: 'KW' },
  { label: 'Saint Lucia', value: 'LC' },
  { label: 'Liechtenstein', value: 'LI' },
  { label: 'Sri Lanka', value: 'LK' },
  { label: 'Lithuania', value: 'LT' },
  { label: 'Luxembourg', value: 'LU' },
  { label: 'Latvia', value: 'LV' },
  { label: 'Morocco', value: 'MA' },
  { label: 'Monaco', value: 'MC' },
  { label: 'Republic of Moldova', value: 'MD' },
  { label: 'Madagascar', value: 'MG' },
  { label: 'North Macedonia', value: 'MK' },
  { label: 'Mongolia', value: 'MN' },
  { label: 'Macau', value: 'MO' },
  { label: 'Malta', value: 'MT' },
  { label: 'Mauritius', value: 'MU' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Malaysia', value: 'MY' },
  { label: 'Namibia', value: 'NA' },
  { label: 'Nigeria', value: 'NG' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'Norway', value: 'NO' },
  { label: 'New Zealand', value: 'NZ' },
  { label: 'Oman', value: 'OM' },
  { label: 'Panama', value: 'PA' },
  { label: 'Peru', value: 'PE' },
  { label: 'Philippines', value: 'PH' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Poland', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Paraguay', value: 'PY' },
  { label: 'Qatar', value: 'QA' },
  { label: 'Romania', value: 'RO' },
  { label: 'Serbia', value: 'RS' },
  { label: 'Rwanda', value: 'RW' },
  { label: 'Saudi Arabia', value: 'SA' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Singapore', value: 'SG' },
  { label: 'Slovenia', value: 'SI' },
  { label: 'Slovakia', value: 'SK' },
  { label: 'Senegal', value: 'SN' },
  { label: 'El Salvador', value: 'SV' },
  { label: 'Thailand', value: 'TH' },
  { label: 'Tunisia', value: 'TN' },
  { label: 'Turkey', value: 'TR' },
  { label: 'Trinidad and Tobago', value: 'TT' },
  { label: 'Taiwan', value: 'TW' },
  { label: 'United Republic of Tanzania', value: 'TZ' },
  { label: 'Uruguay', value: 'UY' },
  { label: 'Uzbekistan', value: 'UZ' },
  { label: 'Vietnam', value: 'VN' },
  { label: 'South Africa', value: 'ZA' },
] as const;

interface FormCountrySelectProps<T extends FieldValues> {
  control: Control<T>;
  name: Path<T>;
  label?: string;
  description?: string;
  disabled?: boolean;
  className?: string;
  triggerClassName?: string;
}

function FormCountrySelect<T extends FieldValues>({ label = 'Country', ...props }: FormCountrySelectProps<T>) {
  return <FormSelect {...props} label={label} options={[...COUNTRY_OPTIONS]} placeholder="Select a country" />;
}

export { COUNTRY_OPTIONS, FormCountrySelect };
