import type { DeviceSpecColumns } from './device-spec.helper';

export const deviceSpecColumnsFixture: DeviceSpecColumns = {
  id: 'device-1',
  name: 'device-1',
  nickname: null,
  systemSerial: null,
  chassisSerial: null,
  serial: null,
  baseboardSerial: null,
  systemUuid: null,
  productSku: null,
  assetTag: null,
  role: null,
  status: 'PLANNED',
  deviceType: null,
  networkType: null,
  architecture: null,
  uefiBoot: null,
  secureBootEnabled: null,
  iommuEnabled: null,
  sriovEnabled: null,
  zoneId: null,
  organizationId: null,
  supplierId: null,
  deviceModelId: null,
  createdAt: new Date('2024-01-01T00:00:00.000Z'),
  updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  deletedAt: null,
};
